// ─────────────────────────────────────────────────────────────────
// src/words/nouns.ts
// Sources: corpus.quran.com · almaany.com/en/dict/ar-en
// ─────────────────────────────────────────────────────────────────
import type { Noun } from "../App";

export const NOUNS: Noun[] = [
  {
    id: "kitab",
    ar: "كِتَاب",
    root: "ك-ت-ب",
    meaning: "book / scripture",
    sentence: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ هُدًى لِلْمُتَّقِينَ",
    sentenceTr: "That is the Book — no doubt in it — guidance for the God-conscious (Quran 2:2)",
    plurals: [
      { ar: "كُتُب", type: "جمع تكسير", meaning: "books — same meaning", shift: false },
      { ar: "كِتَابَات", type: "جمع مؤنث سالم", meaning: "writings / texts — more abstract", shift: true },
    ],
    contexts: [
      { s: "وَأَنْزَلْنَا إِلَيْكَ الْكِتَابَ بِالْحَقِّ", t: "And We revealed to you the Book with truth", m: "Quran 5:48 — the Quran as kitab" },
      { s: "فَمَنْ أُوتِيَ كِتَابَهُ بِيَمِينِهِ", t: "Whoever is given his record in his right hand", m: "Quran 69:19 — record of deeds on Judgment Day" },
      { s: "اشْتَرَى كِتَابًا مِنَ المَكْتَبَة", t: "He bought a book from the library", m: "everyday — any book" },
    ],
    synonym: { ar: "مُصْحَف", meaning: "physical copy of the Quran", distinction: "كِتَاب = any book or divine scripture; مُصْحَف = specifically the physical Quran" },
    antonym: { ar: "جَهْل", meaning: "ignorance — contextual opposite of knowledge/scripture" },
  },
  {
    id: "qalb",
    ar: "قَلْب",
    root: "ق-ل-ب",
    meaning: "heart",
    sentence: "أَلَا بِذِكْرِ اللهِ تَطْمَئِنُّ الْقُلُوبُ",
    sentenceTr: "Verily, with the remembrance of Allah do hearts find rest (Quran 13:28)",
    plurals: [
      { ar: "قُلُوب", type: "جمع تكسير", meaning: "hearts — same meaning", shift: false },
    ],
    contexts: [
      { s: "إِنَّ فِي ذَٰلِكَ لَذِكْرَىٰ لِمَنْ كَانَ لَهُ قَلْبٌ", t: "Indeed in that is a reminder for whoever has a heart", m: "Quran 50:37 — the conscious heart" },
      { s: "كَتَبَ فِي قُلُوبِهِمُ الْإِيمَانَ", t: "He inscribed faith in their hearts", m: "Quran 58:22 — faith written in the heart" },
      { s: "قَلْبُهُ مُطْمَئِنٌّ بِالإِيمَان", t: "His heart is at peace through faith", m: "everyday spiritual state" },
    ],
    synonym: { ar: "فُؤَاد", meaning: "the innermost heart / core of feeling", distinction: "قَلْب = the general heart (thinking and feeling); فُؤَاد = the emotional core, used in Quran for intense feeling e.g. Quran 28:10" },
    antonym: { ar: "قَسْوَة", meaning: "hardness — as in a hard heart (opposite of a soft heart)" },
  },
  {
    id: "rahma",
    ar: "رَحْمَة",
    root: "ر-ح-م",
    meaning: "mercy / compassion",
    sentence: "وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ",
    sentenceTr: "And My mercy encompasses all things (Quran 7:156)",
    plurals: [
      { ar: "رَحَمَات", type: "جمع مؤنث سالم", meaning: "mercies — acts of mercy", shift: false },
    ],
    contexts: [
      { s: "بِسْمِ اللهِ الرَّحْمَٰنِ الرَّحِيمِ", t: "In the name of Allah, the Most Gracious, the Most Merciful", m: "Basmala — رَحْمَة is the root of both الرَّحْمَٰن and الرَّحِيم" },
      { s: "وَمَا أَرْسَلْنَاكَ إِلَّا رَحْمَةً لِلْعَالَمِينَ", t: "And We have not sent you except as a mercy to the worlds", m: "Quran 21:107 — the Prophet as mercy" },
      { s: "أَرْجُو رَحْمَةَ اللهِ فِي كُلِّ أَمْر", t: "I hope for Allah's mercy in every matter", m: "everyday supplication" },
    ],
    synonym: { ar: "شَفَقَة", meaning: "compassion / pity", distinction: "رَحْمَة = mercy with bounty and care (divine or human); شَفَقَة = compassion born of worry/concern for another" },
    antonym: { ar: "عَذَاب", meaning: "punishment / torment" },
  },
  {
    id: "nafs",
    ar: "نَفْس",
    root: "ن-ف-س",
    meaning: "soul / self",
    sentence: "كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ",
    sentenceTr: "Every soul shall taste death (Quran 3:185)",
    plurals: [
      { ar: "أَنْفُس", type: "جمع تكسير", meaning: "souls / selves — same meaning", shift: false },
      { ar: "نُفُوس", type: "جمع تكسير", meaning: "souls — more literary", shift: false },
    ],
    contexts: [
      { s: "وَلَا تَقْتُلُوا أَنْفُسَكُمْ", t: "And do not kill yourselves", m: "Quran 4:29 — prohibition of self-harm" },
      { s: "النَّفْسُ الأَمَّارَةُ بِالسُّوءِ", t: "The soul that commands to evil", m: "Quran 12:53 — the commanding self" },
      { s: "يَتَحَدَّثُ مَعَ نَفْسِهِ", t: "He talks to himself", m: "everyday — speaking to oneself" },
    ],
    synonym: { ar: "رُوح", meaning: "spirit / soul given by Allah", distinction: "نَفْس = the self/soul that acts and is accountable; رُوح = the divine spirit blown into man, more metaphysical" },
    antonym: null,
  },
  {
    id: "nur",
    ar: "نُور",
    root: "ن-و-ر",
    meaning: "light",
    sentence: "اللهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ",
    sentenceTr: "Allah is the Light of the heavens and the earth (Quran 24:35)",
    plurals: [
      { ar: "أَنْوَار", type: "جمع تكسير", meaning: "lights — physical or metaphorical", shift: false },
    ],
    contexts: [
      { s: "يُخْرِجُهُمْ مِنَ الظُّلُمَاتِ إِلَى النُّورِ", t: "He brings them out of darknesses into the light", m: "Quran 2:257 — guidance as light" },
      { s: "الْعِلْمُ نُورٌ", t: "Knowledge is light", m: "famous Arabic proverb" },
      { s: "أَضَاءَ النُّورُ الغُرْفَةَ كُلَّهَا", t: "The light lit up the entire room", m: "everyday — physical light" },
    ],
    synonym: { ar: "ضِيَاء", meaning: "radiant / blazing light", distinction: "نُور = gentle guiding light (used for the moon and guidance); ضِيَاء = intense bright light (used for the sun in Quran 10:5)" },
    antonym: { ar: "ظُلْمَة", meaning: "darkness" },
  },
  {
    id: "ilm",
    ar: "عِلْم",
    root: "ع-ل-م",
    meaning: "knowledge",
    sentence: "وَفَوْقَ كُلِّ ذِي عِلْمٍ عَلِيمٌ",
    sentenceTr: "And above every possessor of knowledge is one more knowing (Quran 12:76)",
    plurals: [
      { ar: "عُلُوم", type: "جمع تكسير", meaning: "sciences / fields of knowledge", shift: true },
    ],
    contexts: [
      { s: "وَقُلْ رَبِّ زِدْنِي عِلْمًا", t: "And say: My Lord, increase me in knowledge", m: "Quran 20:114 — the only dua for increase in the Quran" },
      { s: "اطْلُبُوا الْعِلْمَ مِنَ الْمَهْدِ إِلَى اللَّحْد", t: "Seek knowledge from the cradle to the grave", m: "famous hadith on seeking knowledge" },
      { s: "يَدْرُسُ عِلْمَ الهَنْدَسَةِ فِي الجَامِعَة", t: "He studies engineering at university", m: "everyday — field of study" },
    ],
    synonym: { ar: "مَعْرِفَة", meaning: "experiential knowing / recognition", distinction: "عِلْم = knowledge as a body of learning or divine knowing; مَعْرِفَة = knowing through personal experience or recognition" },
    antonym: { ar: "جَهْل", meaning: "ignorance" },
  },
  {
    id: "sabr",
    ar: "صَبْر",
    root: "ص-ب-ر",
    meaning: "patience / perseverance",
    sentence: "إِنَّ اللهَ مَعَ الصَّابِرِينَ",
    sentenceTr: "Indeed Allah is with the patient (Quran 2:153)",
    plurals: [
      { ar: "لا جمع له", type: "مصدر", meaning: "no plural — it is a masdar (verbal noun)", shift: false },
    ],
    contexts: [
      { s: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ", t: "And seek help through patience and prayer", m: "Quran 2:45 — patience as a tool for worship" },
      { s: "الصَّبْرُ نِصْفُ الْإِيمَان", t: "Patience is half of faith", m: "famous hadith" },
      { s: "يَحْتَاجُ الأَمْرُ إِلَى صَبْرٍ طَوِيل", t: "The matter requires long patience", m: "everyday — needing patience" },
    ],
    synonym: { ar: "تَحَمُّل", meaning: "endurance / tolerance", distinction: "صَبْر = patient restraint with full awareness and acceptance; تَحَمُّل = bearing a burden, more about capacity than spiritual acceptance" },
    antonym: { ar: "جَزَع", meaning: "anxiety / impatience / panic" },
  },
  {
    id: "dua",
    ar: "دُعَاء",
    root: "د-ع-و",
    meaning: "supplication / prayer",
    sentence: "وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ أُجِيبُ دَعْوَةَ الدَّاعِ",
    sentenceTr: "And when My servants ask about Me — I am near. I answer the call of the one who calls (Quran 2:186)",
    plurals: [
      { ar: "أَدْعِيَة", type: "جمع تكسير", meaning: "supplications / prayers — same meaning", shift: false },
    ],
    contexts: [
      { s: "وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ", t: "And your Lord said: Call upon Me and I will respond to you", m: "Quran 40:60 — the command to make dua" },
      { s: "الدُّعَاءُ مُخُّ الْعِبَادَة", t: "Supplication is the essence of worship", m: "hadith — importance of dua" },
      { s: "يَقْرَأُ أَدْعِيَةَ الصَّبَاحِ كُلَّ يَوْم", t: "He reads the morning supplications every day", m: "everyday — morning adhkar" },
    ],
    synonym: { ar: "صَلَاة", meaning: "prayer / connection to Allah", distinction: "دُعَاء = personal supplication in any form; صَلَاة = the formal prescribed prayer with specific movements and recitations" },
    antonym: null,
  },
  {
    id: "iman",
    ar: "إِيمَان",
    root: "أ-م-ن",
    meaning: "faith / belief",
    sentence: "الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُمْ بِذِكْرِ اللهِ",
    sentenceTr: "Those who believed and whose hearts find rest in the remembrance of Allah (Quran 13:28)",
    plurals: [
      { ar: "لا جمع له", type: "مصدر", meaning: "no plural — it is a masdar (verbal noun)", shift: false },
    ],
    contexts: [
      { s: "وَمَا كَانَ اللهُ لِيُضِيعَ إِيمَانَكُمْ", t: "And Allah would not let your faith be lost", m: "Quran 2:143 — faith is precious to Allah" },
      { s: "الْإِيمَانُ بِضْعٌ وَسَبْعُونَ شُعْبَة", t: "Faith has over seventy branches", m: "hadith — faith has many components" },
      { s: "إِيمَانُهُ قَوِيٌّ وَيَظْهَرُ فِي أَفْعَالِه", t: "His faith is strong and shows in his actions", m: "everyday — describing someone's faith" },
    ],
    synonym: { ar: "يَقِين", meaning: "certainty / conviction", distinction: "إِيمَان = faith (belief in the unseen, includes action); يَقِين = certainty beyond doubt, the highest level of إِيمَان" },
    antonym: { ar: "كُفْر", meaning: "disbelief" },
  },
  {
    id: "taqwa",
    ar: "تَقْوَى",
    root: "و-ق-ي",
    meaning: "God-consciousness / piety",
    sentence: "إِنَّ أَكْرَمَكُمْ عِنْدَ اللهِ أَتْقَاكُمْ",
    sentenceTr: "Indeed the most noble of you in the sight of Allah is the most God-conscious (Quran 49:13)",
    plurals: [
      { ar: "لا جمع له", type: "مصدر", meaning: "no plural — abstract quality", shift: false },
    ],
    contexts: [
      { s: "يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللهَ حَقَّ تُقَاتِهِ", t: "O you who believe, fear Allah as He deserves to be feared", m: "Quran 3:102 — command to have taqwa" },
      { s: "وَتَزَوَّدُوا فَإِنَّ خَيْرَ الزَّادِ التَّقْوَى", t: "And take provision — the best provision is taqwa", m: "Quran 2:197 — taqwa as the best provision for the journey" },
      { s: "التَّقْوَى فِي القَلْب", t: "Taqwa is in the heart", m: "hadith — pointing to his chest three times" },
    ],
    synonym: { ar: "وَرَع", meaning: "scrupulous piety / avoidance of doubtful matters", distinction: "تَقْوَى = general God-consciousness and fear of Allah; وَرَع = careful avoidance of even the doubtful, a higher degree of caution" },
    antonym: { ar: "فُجُور", meaning: "wickedness / moral corruption" },
  },
  // 25 additional nouns — add these objects into src/words/nouns.ts inside the NOUNS array
// Sources: corpus.quran.com · almaany.com/en/dict/ar-en

  {
    id: "aql",
    ar: "عَقْل",
    root: "ع-ق-ل",
    meaning: "mind / intellect / reason",
    sentence: "إِنَّ فِي ذَٰلِكَ لَآيَاتٍ لِقَوْمٍ يَعْقِلُونَ",
    sentenceTr: "Indeed in that are signs for people who reason (Quran 2:164)",
    plurals: [
      { ar: "عُقُول", type: "جمع تكسير", meaning: "minds / intellects", shift: false },
    ],
    contexts: [
      { s: "أَفَلَا تَعْقِلُونَ", t: "Will you not use reason?", m: "Quran — repeated challenge to use intellect" },
      { s: "الْعَقْلُ نُورٌ وَالْجَهْلُ ظُلُمَات", t: "The mind is light and ignorance is darkness", m: "Arabic proverb" },
      { s: "يَسْتَخْدِمُ عَقْلَهُ فِي حَلِّ المَسَائِل", t: "He uses his mind to solve problems", m: "everyday — thinking and reasoning" },
    ],
    synonym: { ar: "لُبّ", meaning: "the core of the mind / pure intellect", distinction: "عَقْل = the general faculty of reason used in thinking and deciding; لُبّ = the innermost faculty of pure sound judgment (used in Quran: أُولُو الْأَلْبَابِ — people of understanding)" },
    antonym: { ar: "جَهْل", meaning: "ignorance" },
  },
  {
    id: "lisan",
    ar: "لِسَان",
    root: "ل-س-ن",
    meaning: "tongue / language",
    sentence: "وَمِنْ آيَاتِهِ خَلْقُ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافُ أَلْسِنَتِكُمْ",
    sentenceTr: "Among His signs is the creation of the heavens and earth and the diversity of your tongues (Quran 30:22)",
    plurals: [
      { ar: "أَلْسِنَة", type: "جمع تكسير", meaning: "tongues / languages", shift: false },
      { ar: "أَلْسُن", type: "جمع تكسير", meaning: "tongues — more literary variant", shift: false },
    ],
    contexts: [
      { s: "وَمَا أَرْسَلْنَا مِنْ رَسُولٍ إِلَّا بِلِسَانِ قَوْمِهِ", t: "We never sent a messenger except in the language of his people", m: "Quran 14:4 — revelation in native tongue" },
      { s: "احْفَظْ لِسَانَكَ مِنَ الكَذِب", t: "Guard your tongue from lying", m: "everyday — controlling speech" },
      { s: "يَتَكَلَّمُ بِلِسَانٍ فَصِيح", t: "He speaks with an eloquent tongue", m: "describing eloquent speech" },
    ],
    synonym: { ar: "لُغَة", meaning: "language as a system", distinction: "لِسَان = the physical tongue and also a specific language/dialect; لُغَة = language as a system of communication (more abstract)" },
    antonym: null,
  },
  {
    id: "waqt",
    ar: "وَقْت",
    root: "و-ق-ت",
    meaning: "time",
    sentence: "وَالْعَصْرِ إِنَّ الْإِنْسَانَ لَفِي خُسْرٍ",
    sentenceTr: "By time — indeed mankind is in loss (Quran 103:1-2)",
    plurals: [
      { ar: "أَوْقَات", type: "جمع تكسير", meaning: "times / periods", shift: false },
    ],
    contexts: [
      { s: "إِنَّ الصَّلَاةَ كَانَتْ عَلَى الْمُؤْمِنِينَ كِتَابًا مَوْقُوتًا", t: "Prayer has been ordained at fixed times for the believers", m: "Quran 4:103 — time-bound worship" },
      { s: "الْوَقْتُ كَالسَّيْفِ إِنْ لَمْ تَقْطَعْهُ قَطَعَك", t: "Time is like a sword — if you don't cut it, it cuts you", m: "famous Arabic proverb on time" },
      { s: "يُدِيرُ وَقْتَهُ بِحِكْمَة", t: "He manages his time wisely", m: "everyday — time management" },
    ],
    synonym: { ar: "زَمَن", meaning: "time as an era / epoch", distinction: "وَقْت = a specific point or period of time; زَمَن = time as a flowing era or age, broader and more abstract" },
    antonym: null,
  },
  {
    id: "bayt",
    ar: "بَيْت",
    root: "ب-ي-ت",
    meaning: "house / home",
    sentence: "إِنَّ أَوَّلَ بَيْتٍ وُضِعَ لِلنَّاسِ لَلَّذِي بِبَكَّةَ مُبَارَكًا",
    sentenceTr: "The first house established for people was the one at Makkah — blessed (Quran 3:96)",
    plurals: [
      { ar: "بُيُوت", type: "جمع تكسير", meaning: "houses / homes", shift: false },
      { ar: "أَبْيَات", type: "جمع تكسير", meaning: "verses of poetry / homes (literary)", shift: true },
    ],
    contexts: [
      { s: "وَإِذْ جَعَلْنَا الْبَيْتَ مَثَابَةً لِلنَّاسِ وَأَمْنًا", t: "And when We made the House a place of return and security for people", m: "Quran 2:125 — the Kaaba" },
      { s: "وَقَرْنَ فِي بُيُوتِكُنَّ", t: "And stay in your homes", m: "Quran 33:33" },
      { s: "يَرْجِعُ إِلَى بَيْتِهِ بَعْدَ العَمَل", t: "He returns home after work", m: "everyday — going home" },
    ],
    synonym: { ar: "مَنْزِل", meaning: "dwelling / residence", distinction: "بَيْت = house/home with a sense of belonging and family; مَنْزِل = a place where one stops or resides, more neutral" },
    antonym: null,
  },
  {
    id: "yawm",
    ar: "يَوْم",
    root: "ي-و-م",
    meaning: "day",
    sentence: "يَوْمَ لَا يَنْفَعُ مَالٌ وَلَا بَنُونَ",
    sentenceTr: "The Day when neither wealth nor children will avail (Quran 26:88)",
    plurals: [
      { ar: "أَيَّام", type: "جمع تكسير", meaning: "days", shift: false },
    ],
    contexts: [
      { s: "وَاذْكُرْ يَوْمَ نَحْشُرُ مِنْ كُلِّ أُمَّةٍ فَوْجًا", t: "And remember the Day We will gather from every nation a group", m: "Quran 27:83 — Day of Judgment" },
      { s: "الْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ", t: "This day I have perfected your religion for you", m: "Quran 5:3 — the day of completion of religion" },
      { s: "يَبْدَأُ يَوْمَهُ بِقِرَاءَةِ القُرْآن", t: "He starts his day by reading the Quran", m: "everyday morning routine" },
    ],
    synonym: { ar: "نَهَار", meaning: "daytime (daylight hours)", distinction: "يَوْم = a full day (24 hours) or a significant day/era; نَهَار = only the daytime portion, contrasted with اللَّيْل (night)" },
    antonym: { ar: "لَيْل", meaning: "night" },
  },
  {
    id: "ard",
    ar: "أَرْض",
    root: "أ-ر-ض",
    meaning: "earth / land / ground",
    sentence: "وَلِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
    sentenceTr: "To Allah belongs all that is in the heavens and all that is in the earth (Quran 2:284)",
    plurals: [
      { ar: "أَرَاضِي", type: "جمع تكسير", meaning: "lands / territories", shift: false },
    ],
    contexts: [
      { s: "وَلَا تُفْسِدُوا فِي الْأَرْضِ بَعْدَ إِصْلَاحِهَا", t: "And do not cause corruption in the land after its reformation", m: "Quran 7:56" },
      { s: "إِنَّ الْأَرْضَ لِلَّهِ يُورِثُهَا مَنْ يَشَاءُ", t: "Indeed the earth belongs to Allah — He bequeaths it to whom He wills", m: "Quran 7:128" },
      { s: "سَافَرَ إِلَى أَرْضٍ بَعِيدَة", t: "He travelled to a distant land", m: "everyday — land and geography" },
    ],
    synonym: { ar: "تُرَاب", meaning: "soil / dust", distinction: "أَرْض = the earth as a whole or a stretch of land; تُرَاب = the actual soil/dirt, used for the substance itself (Quran: خَلَقَكُمْ مِنْ تُرَابٍ)" },
    antonym: { ar: "سَمَاء", meaning: "sky / heaven" },
  },
  {
    id: "sama",
    ar: "سَمَاء",
    root: "س-م-و",
    meaning: "sky / heaven",
    sentence: "اللهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ",
    sentenceTr: "Allah is the Light of the heavens and the earth (Quran 24:35)",
    plurals: [
      { ar: "سَمَاوَات", type: "جمع مؤنث سالم", meaning: "heavens / skies", shift: false },
    ],
    contexts: [
      { s: "أَلَمْ تَرَ أَنَّ اللهَ يُسَبِّحُ لَهُ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ", t: "Do you not see that to Allah bow all in the heavens and earth?", m: "Quran 24:41" },
      { s: "وَنَزَّلْنَا مِنَ السَّمَاءِ مَاءً مُبَارَكًا", t: "And We sent down from the sky blessed water", m: "Quran 50:9 — rain from the sky" },
      { s: "نَظَرَ إِلَى السَّمَاءِ وَتَأَمَّلَ النُّجُوم", t: "He looked at the sky and pondered the stars", m: "everyday — looking at the sky" },
    ],
    synonym: { ar: "فَلَك", meaning: "celestial sphere / orbit", distinction: "سَمَاء = the sky/heaven in general; فَلَك = the celestial sphere or orbit of a heavenly body (Quran: كُلٌّ فِي فَلَكٍ يَسْبَحُونَ)" },
    antonym: { ar: "أَرْض", meaning: "earth / ground" },
  },
  {
    id: "maal",
    ar: "مَال",
    root: "م-و-ل",
    meaning: "wealth / money / property",
    sentence: "وَتُحِبُّونَ الْمَالَ حُبًّا جَمًّا",
    sentenceTr: "And you love wealth with immense love (Quran 89:20)",
    plurals: [
      { ar: "أَمْوَال", type: "جمع تكسير", meaning: "wealth / properties / funds", shift: false },
    ],
    contexts: [
      { s: "الْمَالُ وَالْبَنُونَ زِينَةُ الْحَيَاةِ الدُّنْيَا", t: "Wealth and children are the adornment of worldly life", m: "Quran 18:46 — dunya vs akhira" },
      { s: "لَا تَأْكُلُوا أَمْوَالَكُمْ بَيْنَكُمْ بِالْبَاطِلِ", t: "Do not consume each other's wealth unjustly", m: "Quran 2:188" },
      { s: "يُنْفِقُ مِنْ مَالِهِ فِي سَبِيلِ اللهِ", t: "He spends from his wealth in the way of Allah", m: "everyday — charitable giving" },
    ],
    synonym: { ar: "ثَرْوَة", meaning: "fortune / great wealth", distinction: "مَال = wealth in general including money, property, and possessions; ثَرْوَة = substantial wealth / a fortune (more emphasis on abundance)" },
    antonym: { ar: "فَقْر", meaning: "poverty" },
  },
  {
    id: "umma",
    ar: "أُمَّة",
    root: "أ-م-م",
    meaning: "nation / community",
    sentence: "كُنْتُمْ خَيْرَ أُمَّةٍ أُخْرِجَتْ لِلنَّاسِ",
    sentenceTr: "You are the best nation produced for mankind (Quran 3:110)",
    plurals: [
      { ar: "أُمَم", type: "جمع تكسير", meaning: "nations / communities", shift: false },
    ],
    contexts: [
      { s: "كُنْتُمْ خَيْرَ أُمَّةٍ أُخْرِجَتْ لِلنَّاسِ تَأْمُرُونَ بِالْمَعْرُوفِ", t: "You are the best nation produced for mankind — commanding good", m: "Quran 3:110" },
      { s: "وَكَذَٰلِكَ جَعَلْنَاكُمْ أُمَّةً وَسَطًا", t: "And thus We have made you a middle nation", m: "Quran 2:143 — the balanced community" },
      { s: "يَعْمَلُ لِخَيْرِ الأُمَّة", t: "He works for the good of the nation", m: "everyday — serving the community" },
    ],
    synonym: { ar: "شَعْب", meaning: "people / folk", distinction: "أُمَّة = a community united by faith, values, or prophet; شَعْب = a people united by ethnicity, culture, or nationality" },
    antonym: null,
  },
  {
    id: "rasul",
    ar: "رَسُول",
    root: "ر-س-ل",
    meaning: "messenger / prophet",
    sentence: "مُحَمَّدٌ رَسُولُ اللهِ",
    sentenceTr: "Muhammad is the Messenger of Allah (Quran 48:29)",
    plurals: [
      { ar: "رُسُل", type: "جمع تكسير", meaning: "messengers / prophets", shift: false },
    ],
    contexts: [
      { s: "مُحَمَّدٌ رَسُولُ اللهِ وَالَّذِينَ مَعَهُ أَشِدَّاءُ عَلَى الْكُفَّارِ", t: "Muhammad is the Messenger of Allah and those with him are firm against disbelievers", m: "Quran 48:29" },
      { s: "وَمَا مُحَمَّدٌ إِلَّا رَسُولٌ قَدْ خَلَتْ مِنْ قَبْلِهِ الرُّسُلُ", t: "Muhammad is not but a messenger — messengers have passed before him", m: "Quran 3:144" },
      { s: "يُحِبُّ الرَّسُولَ ﷺ وَيَتَّبِعُ سُنَّتَه", t: "He loves the Messenger ﷺ and follows his sunnah", m: "everyday — following the Prophet" },
    ],
    synonym: { ar: "نَبِيّ", meaning: "prophet", distinction: "رَسُول = a messenger sent with a new scripture or law; نَبِيّ = a prophet who may not bring a new law but conveys Allah's messages. Every rasul is a nabi but not vice versa" },
    antonym: null,
  },
  {
    id: "haqq",
    ar: "حَقّ",
    root: "ح-ق-ق",
    meaning: "truth / right / due",
    sentence: "وَقُلْ جَاءَ الْحَقُّ وَزَهَقَ الْبَاطِلُ",
    sentenceTr: "And say: truth has come and falsehood has vanished (Quran 17:81)",
    plurals: [
      { ar: "حُقُوق", type: "جمع تكسير", meaning: "rights / dues", shift: true },
    ],
    contexts: [
      { s: "ذَٰلِكَ بِأَنَّ اللهَ هُوَ الْحَقُّ", t: "That is because Allah is the Truth", m: "Quran 22:6 — Allah as al-Haqq" },
      { s: "وَلَا تَلْبِسُوا الْحَقَّ بِالْبَاطِلِ", t: "And do not mix truth with falsehood", m: "Quran 2:42" },
      { s: "يَطْلُبُ حَقَّهُ بِالطُّرُقِ القَانُونِيَّة", t: "He seeks his rights through legal means", m: "everyday — asserting one's rights" },
    ],
    synonym: { ar: "صِدْق", meaning: "truthfulness / sincerity", distinction: "حَقّ = truth as a reality or established fact / also a right or due; صِدْق = truthfulness in speech and intention — the quality of being honest" },
    antonym: { ar: "بَاطِل", meaning: "falsehood / vanity" },
  },
  {
    id: "amr",
    ar: "أَمْر",
    root: "أ-م-ر",
    meaning: "matter / affair / command",
    sentence: "أَلَا لَهُ الْخَلْقُ وَالْأَمْرُ",
    sentenceTr: "Unquestionably, His is the creation and the command (Quran 7:54)",
    plurals: [
      { ar: "أُمُور", type: "جمع تكسير", meaning: "matters / affairs", shift: true },
      { ar: "أَوَامِر", type: "جمع تكسير", meaning: "commands / orders", shift: true },
    ],
    contexts: [
      { s: "إِنَّمَا أَمْرُهُ إِذَا أَرَادَ شَيْئًا أَنْ يَقُولَ لَهُ كُنْ فَيَكُونُ", t: "His command is only when He intends a thing that He says 'Be' and it is", m: "Quran 36:82 — Allah's command kun fayakun" },
      { s: "وَأَمْرُهُمْ شُورَى بَيْنَهُمْ", t: "And their affairs are conducted by consultation among themselves", m: "Quran 42:38 — shura in community" },
      { s: "هَذَا أَمْرٌ مُهِمٌّ لَا يَجُوزُ تَأْجِيلُهُ", t: "This is an important matter that cannot be delayed", m: "everyday — an important issue" },
    ],
    synonym: { ar: "شَأْن", meaning: "affair / concern / state", distinction: "أَمْر = a matter, affair, or command; شَأْن = one's concern or state of affairs — more personal (Quran: كُلَّ يَوْمٍ هُوَ فِي شَأْنٍ)" },
    antonym: null,
  },
  {
    id: "abd",
    ar: "عَبْد",
    root: "ع-ب-د",
    meaning: "servant / slave / worshipper",
    sentence: "سُبْحَانَ الَّذِي أَسْرَى بِعَبْدِهِ لَيْلًا",
    sentenceTr: "Glory to He who took His servant on a journey by night (Quran 17:1 — Isra)",
    plurals: [
      { ar: "عِبَاد", type: "جمع تكسير", meaning: "servants / worshippers (of Allah)", shift: false },
      { ar: "عَبِيد", type: "جمع تكسير", meaning: "slaves (physical servitude)", shift: true },
    ],
    contexts: [
      { s: "وَعِبَادُ الرَّحْمَٰنِ الَّذِينَ يَمْشُونَ عَلَى الْأَرْضِ هَوْنًا", t: "The servants of the Most Merciful are those who walk upon the earth humbly", m: "Quran 25:63 — qualities of true servants" },
      { s: "وَمَا أَنَا إِلَّا عَبْدٌ مِنْ عِبَادِ اللهِ", t: "I am nothing but a servant from among the servants of Allah", m: "expressing humility" },
      { s: "كُلُّنَا عَبِيدٌ لِلَّهِ نَسْأَلُهُ الرَّحْمَة", t: "We are all servants of Allah, asking Him for mercy", m: "everyday — acknowledging servitude to Allah" },
    ],
    synonym: { ar: "مَمْلُوك", meaning: "owned / enslaved person", distinction: "عَبْد = servant/worshipper of Allah (honorable); also a slave in classical usage; مَمْلُوك = one who is literally owned — neutral term for historical slavery context" },
    antonym: { ar: "رَبّ", meaning: "Lord / master" },
  },
  {
    id: "kalima",
    ar: "كَلِمَة",
    root: "ك-ل-م",
    meaning: "word / statement",
    sentence: "كَلِمَةُ اللهِ هِيَ الْعُلْيَا",
    sentenceTr: "The word of Allah is the highest (Quran 9:40)",
    plurals: [
      { ar: "كَلِمَات", type: "جمع مؤنث سالم", meaning: "words / statements", shift: false },
      { ar: "كَلِم", type: "اسم جمع", meaning: "words (collective)", shift: false },
    ],
    contexts: [
      { s: "وَتَمَّتْ كَلِمَةُ رَبِّكَ صِدْقًا وَعَدْلًا", t: "The word of your Lord is complete in truth and justice", m: "Quran 6:115" },
      { s: "كَلِمَةُ التَّوْحِيدِ لَا إِلَٰهَ إِلَّا اللهُ", t: "The word of tawhid: there is no god but Allah", m: "the greatest kalima in Islam" },
      { s: "قَالَ كَلِمَةً طَيِّبَةً أَثَّرَتْ فِيه", t: "He said a kind word that affected him deeply", m: "everyday — the power of words" },
    ],
    synonym: { ar: "لَفْظ", meaning: "utterance / pronunciation", distinction: "كَلِمَة = a word with meaning and significance; لَفْظ = the physical utterance or pronunciation of a word — more about the sound than the meaning" },
    antonym: null,
  },
  {
    id: "amal",
    ar: "عَمَل",
    root: "ع-م-ل",
    meaning: "deed / work / action",
    sentence: "فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ",
    sentenceTr: "Whoever does an atom's weight of good will see it (Quran 99:7)",
    plurals: [
      { ar: "أَعْمَال", type: "جمع تكسير", meaning: "deeds / actions / works", shift: false },
    ],
    contexts: [
      { s: "الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ", t: "Those who believed and did righteous deeds", m: "Quran — most repeated phrase linking faith and action" },
      { s: "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ", t: "Indeed actions are by intentions", m: "hadith — the foundation of all deeds" },
      { s: "يَبْحَثُ عَنْ عَمَلٍ مُنَاسِبٍ بَعْدَ التَّخَرُّج", t: "He is looking for suitable work after graduation", m: "everyday — job searching" },
    ],
    synonym: { ar: "فِعْل", meaning: "act / action (single)", distinction: "عَمَل = work or deed (often sustained, can be a career or a pattern of action); فِعْل = a single act or action (also used grammatically for verbs)" },
    antonym: { ar: "كَسَل", meaning: "laziness / idleness" },
  },
  {
    id: "hayat",
    ar: "حَيَاة",
    root: "ح-ي-و",
    meaning: "life",
    sentence: "وَمَا الْحَيَاةُ الدُّنْيَا إِلَّا مَتَاعُ الْغُرُورِ",
    sentenceTr: "And the worldly life is nothing but the enjoyment of delusion (Quran 3:185)",
    plurals: [
      { ar: "لا جمع له", type: "مصدر", meaning: "no common plural — abstract noun", shift: false },
    ],
    contexts: [
      { s: "كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ وَإِنَّمَا تُوَفَّوْنَ أُجُورَكُمْ يَوْمَ الْقِيَامَةِ", t: "Every soul will taste death and you will receive your rewards on the Day of Resurrection", m: "Quran 3:185" },
      { s: "الْحَيَاةُ الدُّنْيَا لَعِبٌ وَلَهْوٌ", t: "The worldly life is play and amusement", m: "Quran 6:32 — warning about dunya" },
      { s: "يَعِيشُ حَيَاةً بَسِيطَةً وَمُتَوَاضِعَة", t: "He lives a simple and humble life", m: "everyday — describing a way of life" },
    ],
    synonym: { ar: "عُمُر", meaning: "lifespan / age", distinction: "حَيَاة = life as the state of being alive; عُمُر = the span or duration of one's life — how long you live" },
    antonym: { ar: "مَوْت", meaning: "death" },
  },
  {
    id: "mawt",
    ar: "مَوْت",
    root: "م-و-ت",
    meaning: "death",
    sentence: "كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ",
    sentenceTr: "Every soul shall taste death (Quran 3:185)",
    plurals: [
      { ar: "لا جمع له", type: "مصدر", meaning: "no plural — abstract noun", shift: false },
    ],
    contexts: [
      { s: "أَيْنَمَا تَكُونُوا يُدْرِكُكُمُ الْمَوْتُ", t: "Wherever you may be, death will overtake you", m: "Quran 4:78 — inevitability of death" },
      { s: "وَجَاءَتْ سَكْرَةُ الْمَوْتِ بِالْحَقِّ", t: "And the stupor of death will come with the truth", m: "Quran 50:19" },
      { s: "يَتَذَكَّرُ المَوْتَ كَثِيرًا فَيُحْسِنُ عَمَلَه", t: "He remembers death often and so improves his deeds", m: "everyday — remembering death as motivation" },
    ],
    synonym: { ar: "وَفَاة", meaning: "passing away / decease", distinction: "مَوْت = death in its stark reality; وَفَاة = passing away — a softer term used respectfully, similar to 'passing' in English" },
    antonym: { ar: "حَيَاة", meaning: "life" },
  },
  {
    id: "salat",
    ar: "صَلَاة",
    root: "ص-ل-و",
    meaning: "prayer / salah",
    sentence: "إِنَّ الصَّلَاةَ كَانَتْ عَلَى الْمُؤْمِنِينَ كِتَابًا مَوْقُوتًا",
    sentenceTr: "Prayer has been ordained at fixed times for the believers (Quran 4:103)",
    plurals: [
      { ar: "صَلَوَات", type: "جمع مؤنث سالم", meaning: "prayers / blessings", shift: false },
    ],
    contexts: [
      { s: "وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ", t: "Establish prayer and give zakah", m: "Quran 2:43 — two pillars together" },
      { s: "إِنَّ الصَّلَاةَ تَنْهَى عَنِ الْفَحْشَاءِ وَالْمُنْكَرِ", t: "Indeed prayer prevents immorality and wrongdoing", m: "Quran 29:45 — purpose of salah" },
      { s: "يُحَافِظُ عَلَى الصَّلَوَاتِ الْخَمْسِ فِي وَقْتِهَا", t: "He maintains the five prayers at their proper times", m: "everyday — regular prayer" },
    ],
    synonym: { ar: "دُعَاء", meaning: "supplication / personal prayer", distinction: "صَلَاة = the formal prescribed prayer with specific positions, recitations, and times; دُعَاء = any personal supplication to Allah, informal and at any time" },
    antonym: null,
  },
  {
    id: "rizq",
    ar: "رِزْق",
    root: "ر-ز-ق",
    meaning: "provision / sustenance",
    sentence: "وَفِي السَّمَاءِ رِزْقُكُمْ وَمَا تُوعَدُونَ",
    sentenceTr: "And in the heaven is your provision and whatever you are promised (Quran 51:22)",
    plurals: [
      { ar: "أَرْزَاق", type: "جمع تكسير", meaning: "provisions / livelihoods", shift: false },
    ],
    contexts: [
      { s: "إِنَّ اللهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ", t: "Indeed Allah is the Provider, Owner of power and firm strength", m: "Quran 51:58" },
      { s: "وَمَا مِنْ دَابَّةٍ فِي الْأَرْضِ إِلَّا عَلَى اللهِ رِزْقُهَا", t: "There is no creature on earth but that its provision is upon Allah", m: "Quran 11:6" },
      { s: "يَسْعَى فِي طَلَبِ الرِّزْقِ لِعَائِلَتِهِ", t: "He strives to earn provision for his family", m: "everyday — earning a living" },
    ],
    synonym: { ar: "قُوت", meaning: "daily sustenance / bare necessities", distinction: "رِزْق = all provision from Allah including food, wealth, knowledge, and good; قُوت = the minimum daily sustenance needed to survive" },
    antonym: { ar: "فَقْر", meaning: "poverty / need" },
  },
  {
    id: "deen",
    ar: "دِين",
    root: "د-ي-ن",
    meaning: "religion / way of life / judgment",
    sentence: "إِنَّ الدِّينَ عِنْدَ اللهِ الْإِسْلَامُ",
    sentenceTr: "Indeed the religion with Allah is Islam (Quran 3:19)",
    plurals: [
      { ar: "أَدْيَان", type: "جمع تكسير", meaning: "religions / faiths", shift: false },
    ],
    contexts: [
      { s: "لَكُمْ دِينُكُمْ وَلِيَ دِينِ", t: "For you is your religion and for me is my religion", m: "Quran 109:6 — tolerance and distinction" },
      { s: "الْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ", t: "This day I have perfected your religion for you", m: "Quran 5:3 — completion of Islam" },
      { s: "يَتَعَلَّمُ دِينَهُ مِنَ المَصَادِرِ الصَّحِيحَة", t: "He learns his religion from authentic sources", m: "everyday — seeking Islamic knowledge" },
    ],
    synonym: { ar: "مِلَّة", meaning: "creed / religious tradition / community", distinction: "دِين = religion as a complete system of belief and practice; مِلَّة = the creed or faith tradition of a particular people (Quran: مِلَّةَ إِبْرَاهِيمَ — the way of Ibrahim)" },
    antonym: { ar: "كُفْر", meaning: "disbelief" },
  },
  {
    id: "nabi",
    ar: "نَبِيّ",
    root: "ن-ب-أ",
    meaning: "prophet",
    sentence: "مَا كَانَ مُحَمَّدٌ أَبَا أَحَدٍ مِنْ رِجَالِكُمْ وَلَٰكِنْ رَسُولَ اللهِ وَخَاتَمَ النَّبِيِّينَ",
    sentenceTr: "Muhammad is not the father of any of your men but the Messenger of Allah and the seal of the prophets (Quran 33:40)",
    plurals: [
      { ar: "أَنْبِيَاء", type: "جمع تكسير", meaning: "prophets", shift: false },
    ],
    contexts: [
      { s: "وَخَاتَمَ النَّبِيِّينَ", t: "And the seal of the prophets", m: "Quran 33:40 — the Prophet ﷺ as the last" },
      { s: "إِنَّا أَوْحَيْنَا إِلَيْكَ كَمَا أَوْحَيْنَا إِلَى نُوحٍ وَالنَّبِيِّينَ", t: "We revealed to you as We revealed to Nuh and the prophets", m: "Quran 4:163" },
      { s: "يُعَلِّمُ أَبْنَاءَهُ سِيرَةَ الأَنْبِيَاء", t: "He teaches his children the stories of the prophets", m: "everyday — Islamic education" },
    ],
    synonym: { ar: "رَسُول", meaning: "messenger sent with a new scripture", distinction: "نَبِيّ = a prophet who receives revelation but may not bring new law; رَسُول = a messenger sent with a new scripture or law. Every rasul is a nabi but not every nabi is a rasul" },
    antonym: null,
  },
  {
    id: "janna",
    ar: "جَنَّة",
    root: "ج-ن-ن",
    meaning: "paradise / garden",
    sentence: "وَبَشِّرِ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أَنَّ لَهُمْ جَنَّاتٍ",
    sentenceTr: "Give good news to those who believe and do good deeds that they will have gardens (Quran 2:25)",
    plurals: [
      { ar: "جَنَّات", type: "جمع مؤنث سالم", meaning: "gardens / paradises", shift: false },
    ],
    contexts: [
      { s: "أُعِدَّتْ لِلْمُتَّقِينَ", t: "Prepared for the God-conscious", m: "Quran 3:133 — paradise for the righteous" },
      { s: "فِيهَا مَا تَشْتَهِيهِ الْأَنْفُسُ وَتَلَذُّ الْأَعْيُنُ", t: "In it is what souls desire and what delights the eyes", m: "Quran 43:71 — description of paradise" },
      { s: "نَسْأَلُ اللهَ الجَنَّةَ وَنَعُوذُ بِهِ مِنَ النَّار", t: "We ask Allah for paradise and seek refuge with Him from the fire", m: "everyday dua" },
    ],
    synonym: { ar: "فِرْدَوْس", meaning: "the highest level of paradise", distinction: "جَنَّة = paradise in general; فِرْدَوْس = the highest garden of paradise (hadith: ask Allah for al-Firdaws — the highest of paradise)" },
    antonym: { ar: "نَار", meaning: "fire / hell" },
  },
  {
    id: "nar",
    ar: "نَار",
    root: "ن-و-ر",
    meaning: "fire / hell",
    sentence: "وَاتَّقُوا النَّارَ الَّتِي أُعِدَّتْ لِلْكَافِرِينَ",
    sentenceTr: "And fear the fire prepared for the disbelievers (Quran 3:131)",
    plurals: [
      { ar: "نِيرَان", type: "جمع تكسير", meaning: "fires", shift: false },
    ],
    contexts: [
      { s: "وَاتَّقُوا النَّارَ الَّتِي أُعِدَّتْ لِلْكَافِرِينَ", t: "And fear the fire prepared for the disbelievers", m: "Quran 3:131" },
      { s: "يَا أَيُّهَا الَّذِينَ آمَنُوا قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا", t: "O believers, protect yourselves and your families from a fire", m: "Quran 66:6 — responsibility to family" },
      { s: "نَعُوذُ بِاللهِ مِنَ النَّارِ", t: "We seek refuge with Allah from the fire", m: "everyday dua" },
    ],
    synonym: { ar: "جَهَنَّم", meaning: "hell / Gehenna", distinction: "نَار = fire — used both for physical fire and hellfire; جَهَنَّم = the specific name for hell in the Quran, always referring to the place of punishment" },
    antonym: { ar: "جَنَّة", meaning: "paradise" },
  },
  {
    id: "aaya",
    ar: "آيَة",
    root: "أ-ي-ي",
    meaning: "sign / verse / miracle",
    sentence: "إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ آيَاتٍ لِأُولِي الْأَلْبَابِ",
    sentenceTr: "In the creation of the heavens and earth are signs for people of understanding (Quran 3:190)",
    plurals: [
      { ar: "آيَات", type: "جمع مؤنث سالم", meaning: "signs / verses / miracles", shift: false },
    ],
    contexts: [
      { s: "تِلْكَ آيَاتُ الْكِتَابِ الْمُبِينِ", t: "These are the verses of the clear Book", m: "Quran — opening of multiple surahs" },
      { s: "وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُمْ مِنْ أَنْفُسِكُمْ أَزْوَاجًا", t: "And among His signs is that He created for you spouses", m: "Quran 30:21 — marriage as a divine sign" },
      { s: "يَتَدَبَّرُ آيَاتِ الْقُرْآنِ بَعْدَ الفَجْر", t: "He reflects on the verses of the Quran after Fajr", m: "everyday — Quran study" },
    ],
    synonym: { ar: "دَلِيل", meaning: "proof / evidence", distinction: "آيَة = a sign from Allah in creation or revelation that points to His existence and power; دَلِيل = a proof or argument used to establish a conclusion (more logical/evidential)" },
    antonym: null,
  },
  
];