// ─────────────────────────────────────────────────────────────────
// src/words/verbs.ts
// Sources: corpus.quran.com · almaany.com/en/dict/ar-en
// ─────────────────────────────────────────────────────────────────
import type { Verb } from "../App";

export const VERBS: Verb[] = [
  {
    id: "kataba",
    ar: "كَتَبَ",
    root: "ك-ت-ب",
    form: "Form I",
    meaning: "to write",
    meanings: ["to write", "to prescribe / ordain", "to decree / record"],
    sentence: "كُتِبَ عَلَيْكُمُ الصِّيَامُ",
    sentenceTr: "Fasting has been prescribed for you (Quran 2:183)",
    contexts: [
      { s: "فَوَيْلٌ لِلَّذِينَ يَكْتُبُونَ الْكِتَابَ بِأَيْدِيهِمْ", t: "Woe to those who write the scripture with their own hands", m: "physical writing — Quran 2:79" },
      { s: "كَتَبَ اللهُ لَأَغْلِبَنَّ أَنَا وَرُسُلِي", t: "Allah has decreed: I and My messengers will prevail", m: "divine decree — Quran 58:21" },
      { s: "كَتَبَ الطَّالِبُ رِسَالَةً إِلَى أُمِّهِ", t: "The student wrote a letter to his mother", m: "everyday writing" },
    ],
    masdar: "كِتَابَة / كَتْب",
    fail: "كَاتِب",
    mafool: "مَكْتُوب",
    conjugation: {
      past:    ["كَتَبَ","كَتَبَتْ","كَتَبَا","كَتَبَتَا","كَتَبُوا","كَتَبْنَ","كَتَبْتَ","كَتَبْتِ","كَتَبْتُمَا","كَتَبْتُمْ","كَتَبْتُنَّ","كَتَبْتُ","كَتَبْنَا"],
      present: ["يَكْتُبُ","تَكْتُبُ","يَكْتُبَانِ","تَكْتُبَانِ","يَكْتُبُونَ","يَكْتُبْنَ","تَكْتُبُ","تَكْتُبِينَ","تَكْتُبَانِ","تَكْتُبُونَ","تَكْتُبْنَ","أَكْتُبُ","نَكْتُبُ"],
    },
  },
  {
    id: "alima",
    ar: "عَلِمَ",
    root: "ع-ل-م",
    form: "Form I",
    meaning: "to know",
    meanings: ["to know", "to be aware of", "to learn / come to know"],
    sentence: "وَاللهُ بِكُلِّ شَيْءٍ عَلِيمٌ",
    sentenceTr: "And Allah is All-Knowing of everything (Quran 2:282)",
    contexts: [
      { s: "يَعْلَمُ مَا فِي السَّمَاوَاتِ وَالْأَرْضِ", t: "He knows what is in the heavens and the earth", m: "divine knowledge — Quran 3:29" },
      { s: "عَلِمَ الطَّالِبُ الجَوَابَ", t: "The student knew the answer", m: "everyday knowing" },
      { s: "أَلَمْ تَعْلَمْ أَنَّ اللهَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ", t: "Did you not know that Allah is over all things capable?", m: "rhetorical question — Quran 2:106" },
    ],
    masdar: "عِلْم",
    fail: "عَالِم",
    mafool: "مَعْلُوم",
    conjugation: {
      past:    ["عَلِمَ","عَلِمَتْ","عَلِمَا","عَلِمَتَا","عَلِمُوا","عَلِمْنَ","عَلِمْتَ","عَلِمْتِ","عَلِمْتُمَا","عَلِمْتُمْ","عَلِمْتُنَّ","عَلِمْتُ","عَلِمْنَا"],
      present: ["يَعْلَمُ","تَعْلَمُ","يَعْلَمَانِ","تَعْلَمَانِ","يَعْلَمُونَ","يَعْلَمْنَ","تَعْلَمُ","تَعْلَمِينَ","تَعْلَمَانِ","تَعْلَمُونَ","تَعْلَمْنَ","أَعْلَمُ","نَعْلَمُ"],
    },
  },
  {
    id: "qala",
    ar: "قَالَ",
    root: "ق-و-ل",
    form: "Form I",
    meaning: "to say",
    meanings: ["to say", "to speak", "to tell / utter"],
    sentence: "قَالَ رَبِّ اشْرَحْ لِي صَدْرِي",
    sentenceTr: "He said: My Lord, expand for me my breast (Quran 20:25)",
    contexts: [
      { s: "قَالَ إِنِّي عَبْدُ اللهِ", t: "He said: Indeed I am a servant of Allah", m: "Quran 19:30 — Isa (AS) speaking" },
      { s: "قَالَ المُعَلِّمُ لِلطُّلَّابِ ادْرُسُوا", t: "The teacher said to the students: study", m: "everyday speech" },
      { s: "قَالَ لَهُ صَاحِبُهُ وَهُوَ يُحَاوِرُهُ", t: "His companion said to him while conversing", m: "dialogue — Quran 18:37" },
    ],
    masdar: "قَوْل",
    fail: "قَائِل",
    mafool: "مَقُول",
    conjugation: {
      past:    ["قَالَ","قَالَتْ","قَالَا","قَالَتَا","قَالُوا","قُلْنَ","قُلْتَ","قُلْتِ","قُلْتُمَا","قُلْتُمْ","قُلْتُنَّ","قُلْتُ","قُلْنَا"],
      present: ["يَقُولُ","تَقُولُ","يَقُولَانِ","تَقُولَانِ","يَقُولُونَ","يَقُلْنَ","تَقُولُ","تَقُولِينَ","تَقُولَانِ","تَقُولُونَ","تَقُلْنَ","أَقُولُ","نَقُولُ"],
    },
  },
  {
    id: "darasa",
    ar: "دَرَسَ",
    root: "د-ر-س",
    form: "Form I",
    meaning: "to study",
    meanings: ["to study", "to learn / read", "to examine / investigate"],
    sentence: "وَدَرَسُوا مَا فِيهِ",
    sentenceTr: "And they studied what was in it (Quran 7:169)",
    contexts: [
      { s: "وَدَرَسُوا مَا فِيهِ وَقَالُوا سَيُغْفَرُ لَنَا", t: "They studied what was in it and said: we will be forgiven", m: "Quran 7:169 — studying scripture" },
      { s: "يَدْرُسُ الطَّالِبُ اللُّغَةَ العَرَبِيَّةَ كُلَّ يَوْم", t: "The student studies Arabic every day", m: "daily study routine" },
      { s: "دَرَسَ الدَّرْسَ حَتَّى فَهِمَهُ", t: "He studied the lesson until he understood it", m: "academic context" },
    ],
    masdar: "دِرَاسَة",
    fail: "دَارِس",
    mafool: "مَدْرُوس",
    conjugation: {
      past:    ["دَرَسَ","دَرَسَتْ","دَرَسَا","دَرَسَتَا","دَرَسُوا","دَرَسْنَ","دَرَسْتَ","دَرَسْتِ","دَرَسْتُمَا","دَرَسْتُمْ","دَرَسْتُنَّ","دَرَسْتُ","دَرَسْنَا"],
      present: ["يَدْرُسُ","تَدْرُسُ","يَدْرُسَانِ","تَدْرُسَانِ","يَدْرُسُونَ","يَدْرُسْنَ","تَدْرُسُ","تَدْرُسِينَ","تَدْرُسَانِ","تَدْرُسُونَ","تَدْرُسْنَ","أَدْرُسُ","نَدْرُسُ"],
    },
  },
  {
    id: "rahima",
    ar: "رَحِمَ",
    root: "ر-ح-م",
    form: "Form I",
    meaning: "to show mercy",
    meanings: ["to show mercy", "to have compassion for", "to be merciful toward"],
    sentence: "وَرَبُّكَ الغَفُورُ ذُو الرَّحْمَةِ",
    sentenceTr: "And your Lord is the Forgiving, Owner of Mercy (Quran 18:58)",
    contexts: [
      { s: "إِنَّ اللهَ بِالنَّاسِ لَرَءُوفٌ رَحِيمٌ", t: "Indeed Allah is Kind and Merciful to the people", m: "divine attribute — Quran 2:143" },
      { s: "رَحِمَ اللهُ عَبْدًا قَالَ الحَقَّ", t: "May Allah have mercy on a servant who spoke the truth", m: "supplication / hadith usage" },
      { s: "رَحِمَ الأَبُ ابْنَهُ الصَّغِيرَ", t: "The father showed mercy to his young son", m: "family / everyday context" },
    ],
    masdar: "رَحْمَة",
    fail: "رَاحِم",
    mafool: "مَرْحُوم",
    conjugation: {
      past:    ["رَحِمَ","رَحِمَتْ","رَحِمَا","رَحِمَتَا","رَحِمُوا","رَحِمْنَ","رَحِمْتَ","رَحِمْتِ","رَحِمْتُمَا","رَحِمْتُمْ","رَحِمْتُنَّ","رَحِمْتُ","رَحِمْنَا"],
      present: ["يَرْحَمُ","تَرْحَمُ","يَرْحَمَانِ","تَرْحَمَانِ","يَرْحَمُونَ","يَرْحَمْنَ","تَرْحَمُ","تَرْحَمِينَ","تَرْحَمَانِ","تَرْحَمُونَ","تَرْحَمْنَ","أَرْحَمُ","نَرْحَمُ"],
    },
  },
  {
    id: "amana",
    ar: "آمَنَ",
    root: "أ-م-ن",
    form: "Form IV",
    meaning: "to believe / have faith",
    meanings: ["to believe", "to have faith", "to trust / feel secure"],
    sentence: "آمَنَ الرَّسُولُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَبِّهِ",
    sentenceTr: "The Messenger believed in what was revealed to him from his Lord (Quran 2:285)",
    contexts: [
      { s: "الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ", t: "Those who believed and did righteous deeds", m: "Quran — most repeated phrase in Quran" },
      { s: "آمَنْتُ بِاللهِ وَمَلَائِكَتِهِ وَكُتُبِهِ", t: "I believed in Allah, His angels, and His books", m: "declaration of faith" },
      { s: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", t: "None of you truly believes until he loves for his brother what he loves for himself", m: "hadith — condition of true faith" },
    ],
    masdar: "إِيمَان",
    fail: "مُؤْمِن",
    mafool: "مُؤْمَن بِهِ",
    conjugation: {
      past:    ["آمَنَ","آمَنَتْ","آمَنَا","آمَنَتَا","آمَنُوا","آمَنَّ","آمَنْتَ","آمَنْتِ","آمَنْتُمَا","آمَنْتُمْ","آمَنْتُنَّ","آمَنْتُ","آمَنَّا"],
      present: ["يُؤْمِنُ","تُؤْمِنُ","يُؤْمِنَانِ","تُؤْمِنَانِ","يُؤْمِنُونَ","يُؤْمِنَّ","تُؤْمِنُ","تُؤْمِنِينَ","تُؤْمِنَانِ","تُؤْمِنُونَ","تُؤْمِنَّ","أُؤْمِنُ","نُؤْمِنُ"],
    },
  },
  {
    id: "sabara",
    ar: "صَبَرَ",
    root: "ص-ب-ر",
    form: "Form I",
    meaning: "to be patient",
    meanings: ["to be patient", "to endure / persevere", "to restrain oneself"],
    sentence: "وَاصْبِرُوا إِنَّ اللهَ مَعَ الصَّابِرِينَ",
    sentenceTr: "And be patient — indeed Allah is with the patient (Quran 8:46)",
    contexts: [
      { s: "وَبَشِّرِ الصَّابِرِينَ الَّذِينَ إِذَا أَصَابَتْهُمْ مُصِيبَةٌ قَالُوا إِنَّا لِلهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ", t: "Give glad tidings to the patient who, when afflicted, say: to Allah we belong and to Him we return", m: "Quran 2:155-156" },
      { s: "صَبَرَ عَلَى الأَذَى وَلَمْ يَشْكُ", t: "He was patient through harm and did not complain", m: "character description" },
      { s: "اصْبِرْ عَلَى مَا يَقُولُونَ", t: "Be patient over what they say", m: "Quran 20:130 — command to the Prophet" },
    ],
    masdar: "صَبْر",
    fail: "صَابِر",
    mafool: "مَصْبُور عَلَيْهِ",
    conjugation: {
      past:    ["صَبَرَ","صَبَرَتْ","صَبَرَا","صَبَرَتَا","صَبَرُوا","صَبَرْنَ","صَبَرْتَ","صَبَرْتِ","صَبَرْتُمَا","صَبَرْتُمْ","صَبَرْتُنَّ","صَبَرْتُ","صَبَرْنَا"],
      present: ["يَصْبِرُ","تَصْبِرُ","يَصْبِرَانِ","تَصْبِرَانِ","يَصْبِرُونَ","يَصْبِرْنَ","تَصْبِرُ","تَصْبِرِينَ","تَصْبِرَانِ","تَصْبِرُونَ","تَصْبِرْنَ","أَصْبِرُ","نَصْبِرُ"],
    },
  },
  {
    id: "dhakara",
    ar: "ذَكَرَ",
    root: "ذ-ك-ر",
    form: "Form I",
    meaning: "to remember / mention",
    meanings: ["to remember", "to mention / speak of", "to invoke / make dhikr"],
    sentence: "فَاذْكُرُونِي أَذْكُرْكُمْ",
    sentenceTr: "So remember Me and I will remember you (Quran 2:152)",
    contexts: [
      { s: "الَّذِينَ يَذْكُرُونَ اللهَ قِيَامًا وَقُعُودًا وَعَلَى جُنُوبِهِمْ", t: "Those who remember Allah standing, sitting, and on their sides", m: "Quran 3:191 — continuous dhikr" },
      { s: "وَاذْكُرْ رَبَّكَ كَثِيرًا", t: "And remember your Lord much", m: "Quran 3:41 — command to dhikr" },
      { s: "ذَكَرَ صَدِيقَهُ القَدِيمَ بِخَيْر", t: "He remembered his old friend fondly", m: "everyday — remembering someone" },
    ],
    masdar: "ذِكْر",
    fail: "ذَاكِر",
    mafool: "مَذْكُور",
    conjugation: {
      past:    ["ذَكَرَ","ذَكَرَتْ","ذَكَرَا","ذَكَرَتَا","ذَكَرُوا","ذَكَرْنَ","ذَكَرْتَ","ذَكَرْتِ","ذَكَرْتُمَا","ذَكَرْتُمْ","ذَكَرْتُنَّ","ذَكَرْتُ","ذَكَرْنَا"],
      present: ["يَذْكُرُ","تَذْكُرُ","يَذْكُرَانِ","تَذْكُرَانِ","يَذْكُرُونَ","يَذْكُرْنَ","تَذْكُرُ","تَذْكُرِينَ","تَذْكُرَانِ","تَذْكُرُونَ","تَذْكُرْنَ","أَذْكُرُ","نَذْكُرُ"],
    },
  },
  {
    id: "shaghala",
    ar: "شَغَلَ",
    root: "ش-غ-ل",
    form: "Form I",
    meaning: "to occupy / keep busy",
    meanings: ["to occupy / keep busy", "to preoccupy", "to engage / absorb"],
    sentence: "شَغَلَتْنَا أَمْوَالُنَا وَأَهْلُونَا",
    sentenceTr: "Our wealth and our families kept us busy (Quran 48:11)",
    contexts: [
      { s: "شَغَلَتْنَا أَمْوَالُنَا وَأَهْلُونَا فَاسْتَغْفِرْ لَنَا", t: "Our wealth and families kept us occupied so ask forgiveness for us", m: "Quran 48:11 — excuse of the hypocrites" },
      { s: "إِنَّهُمْ فِي شُغُلٍ فَاكِهُونَ", t: "Indeed they will be in occupation, enjoying themselves", m: "Quran 36:55 — people of paradise" },
      { s: "شَغَلَ العَمَلُ وَقْتَهُ كُلَّهُ", t: "Work occupied all of his time", m: "everyday — being busy" },
    ],
    masdar: "شُغْل",
    fail: "شَاغِل",
    mafool: "مَشْغُول",
    conjugation: {
      past:    ["شَغَلَ","شَغَلَتْ","شَغَلَا","شَغَلَتَا","شَغَلُوا","شَغَلْنَ","شَغَلْتَ","شَغَلْتِ","شَغَلْتُمَا","شَغَلْتُمْ","شَغَلْتُنَّ","شَغَلْتُ","شَغَلْنَا"],
      present: ["يَشْغَلُ","تَشْغَلُ","يَشْغَلَانِ","تَشْغَلَانِ","يَشْغَلُونَ","يَشْغَلْنَ","تَشْغَلُ","تَشْغَلِينَ","تَشْغَلَانِ","تَشْغَلُونَ","تَشْغَلْنَ","أَشْغَلُ","نَشْغَلُ"],
    },
  },
  {
    id: "sakana",
    ar: "سَكَنَ",
    root: "س-ك-ن",
    form: "Form I",
    meaning: "to dwell / reside",
    meanings: ["to dwell / reside", "to be still / calm", "to settle / inhabit"],
    sentence: "وَجَعَلَ اللَّيْلَ سَكَنًا",
    sentenceTr: "And He made the night a time of rest (Quran 6:96)",
    contexts: [
      { s: "وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُمْ مِنْ أَنْفُسِكُمْ أَزْوَاجًا لِتَسْكُنُوا إِلَيْهَا", t: "And among His signs is that He created for you spouses that you may find tranquility in them", m: "Quran 30:21 — marriage and peace" },
      { s: "يَسْكُنُ فِي شَقَّةٍ قَرِيبَةٍ مِنَ الجَامِعَة", t: "He lives in an apartment near the university", m: "everyday — where someone lives" },
      { s: "سَكَنَتِ الرِّيحُ بَعْدَ العَاصِفَة", t: "The wind calmed after the storm", m: "physical stillness" },
    ],
    masdar: "سُكُون / سَكَن",
    fail: "سَاكِن",
    mafool: "مَسْكُون",
    conjugation: {
      past:    ["سَكَنَ","سَكَنَتْ","سَكَنَا","سَكَنَتَا","سَكَنُوا","سَكَنَّ","سَكَنْتَ","سَكَنْتِ","سَكَنْتُمَا","سَكَنْتُمْ","سَكَنْتُنَّ","سَكَنْتُ","سَكَنَّا"],
      present: ["يَسْكُنُ","تَسْكُنُ","يَسْكُنَانِ","تَسْكُنَانِ","يَسْكُنُونَ","يَسْكُنَّ","تَسْكُنُ","تَسْكُنِينَ","تَسْكُنَانِ","تَسْكُنُونَ","تَسْكُنَّ","أَسْكُنُ","نَسْكُنُ"],
    },
  },
  // ── NEW VERBS — paste these inside the VERBS array in verbs.ts ──
  {
    id: "samiaa",
    ar: "سَمِعَ",
    root: "س-م-ع",
    form: "Form I",
    meaning: "to hear / listen",
    meanings: ["to hear", "to listen", "to obey / heed"],
    sentence: "سَمِعْنَا وَأَطَعْنَا",
    sentenceTr: "We heard and we obeyed (Quran 2:285)",
    contexts: [
      { s: "قَدْ سَمِعَ اللهُ قَوْلَ الَّتِي تُجَادِلُكَ فِي زَوْجِهَا", t: "Allah has heard the speech of the one who argues with you about her husband", m: "Quran 58:1 — Allah hears all" },
      { s: "وَإِذَا سَمِعُوا مَا أُنْزِلَ إِلَى الرَّسُولِ تَرَىٰ أَعْيُنَهُمْ تَفِيضُ مِنَ الدَّمْعِ", t: "When they heard what was revealed to the Messenger their eyes overflow with tears", m: "Quran 5:83 — hearing the Quran with emotion" },
      { s: "سَمِعَ الطَّالِبُ المُحَاضَرَةَ بِانْتِبَاهٍ", t: "The student listened to the lecture attentively", m: "everyday — attentive listening" },
    ],
    masdar: "سَمْع / سَمَاع",
    fail: "سَامِع",
    mafool: "مَسْمُوع",
    conjugation: {
      past:    ["سَمِعَ","سَمِعَتْ","سَمِعَا","سَمِعَتَا","سَمِعُوا","سَمِعْنَ","سَمِعْتَ","سَمِعْتِ","سَمِعْتُمَا","سَمِعْتُمْ","سَمِعْتُنَّ","سَمِعْتُ","سَمِعْنَا"],
      present: ["يَسْمَعُ","تَسْمَعُ","يَسْمَعَانِ","تَسْمَعَانِ","يَسْمَعُونَ","يَسْمَعْنَ","تَسْمَعُ","تَسْمَعِينَ","تَسْمَعَانِ","تَسْمَعُونَ","تَسْمَعْنَ","أَسْمَعُ","نَسْمَعُ"],
    },
  },
  {
    id: "nazala",
    ar: "نَزَلَ",
    root: "ن-ز-ل",
    form: "Form I",
    meaning: "to descend / come down",
    meanings: ["to descend / come down", "to be revealed", "to arrive / alight"],
    sentence: "نَزَلَ بِهِ الرُّوحُ الْأَمِينُ",
    sentenceTr: "The Trustworthy Spirit brought it down (Quran 26:193)",
    contexts: [
      { s: "إِنَّا أَنْزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ", t: "Indeed We sent it down on the Night of Decree", m: "Quran 97:1 — revelation of the Quran" },
      { s: "وَنَزَّلْنَا مِنَ السَّمَاءِ مَاءً مُبَارَكًا", t: "And We sent down from the sky blessed water", m: "Quran 50:9 — rain as blessing" },
      { s: "نَزَلَ الضَّيْفُ عِنْدَنَا اللَّيْلَةَ", t: "The guest arrived and stayed with us tonight", m: "everyday — a guest arriving" },
    ],
    masdar: "نُزُول",
    fail: "نَازِل",
    mafool: "مَنْزُول",
    conjugation: {
      past:    ["نَزَلَ","نَزَلَتْ","نَزَلَا","نَزَلَتَا","نَزَلُوا","نَزَلْنَ","نَزَلْتَ","نَزَلْتِ","نَزَلْتُمَا","نَزَلْتُمْ","نَزَلْتُنَّ","نَزَلْتُ","نَزَلْنَا"],
      present: ["يَنْزِلُ","تَنْزِلُ","يَنْزِلَانِ","تَنْزِلَانِ","يَنْزِلُونَ","يَنْزِلْنَ","تَنْزِلُ","تَنْزِلِينَ","تَنْزِلَانِ","تَنْزِلُونَ","تَنْزِلْنَ","أَنْزِلُ","نَنْزِلُ"],
    },
  },
  {
    id: "amara",
    ar: "أَمَرَ",
    root: "أ-م-ر",
    form: "Form I",
    meaning: "to command / order",
    meanings: ["to command / order", "to instruct", "to enjoin"],
    sentence: "إِنَّ اللهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ",
    sentenceTr: "Indeed Allah commands justice and good conduct (Quran 16:90)",
    contexts: [
      { s: "إِنَّ اللهَ يَأْمُرُكُمْ أَنْ تُؤَدُّوا الْأَمَانَاتِ إِلَىٰ أَهْلِهَا", t: "Indeed Allah commands you to render trusts to their rightful owners", m: "Quran 4:58 — divine command" },
      { s: "أَمَرَ النَّبِيُّ ﷺ بِصِلَةِ الرَّحِم", t: "The Prophet commanded maintaining family ties", m: "hadith context" },
      { s: "أَمَرَ المُدِيرُ المُوَظَّفِينَ بِإِنْهَاءِ العَمَل", t: "The manager ordered the employees to finish the work", m: "everyday — workplace command" },
    ],
    masdar: "أَمْر",
    fail: "آمِر",
    mafool: "مَأْمُور",
    conjugation: {
      past:    ["أَمَرَ","أَمَرَتْ","أَمَرَا","أَمَرَتَا","أَمَرُوا","أَمَرْنَ","أَمَرْتَ","أَمَرْتِ","أَمَرْتُمَا","أَمَرْتُمْ","أَمَرْتُنَّ","أَمَرْتُ","أَمَرْنَا"],
      present: ["يَأْمُرُ","تَأْمُرُ","يَأْمُرَانِ","تَأْمُرَانِ","يَأْمُرُونَ","يَأْمُرْنَ","تَأْمُرُ","تَأْمُرِينَ","تَأْمُرَانِ","تَأْمُرُونَ","تَأْمُرْنَ","آمُرُ","نَأْمُرُ"],
    },
  },
  {
    id: "akala",
    ar: "أَكَلَ",
    root: "أ-ك-ل",
    form: "Form I",
    meaning: "to eat",
    meanings: ["to eat", "to consume / devour", "to spend / use up"],
    sentence: "كُلُوا مِنْ طَيِّبَاتِ مَا رَزَقْنَاكُمْ",
    sentenceTr: "Eat of the good things We have provided for you (Quran 2:57)",
    contexts: [
      { s: "كُلُوا وَاشْرَبُوا وَلَا تُسْرِفُوا", t: "Eat and drink but do not be excessive", m: "Quran 7:31 — moderation in eating" },
      { s: "وَلَا تَأْكُلُوا أَمْوَالَكُمْ بَيْنَكُمْ بِالْبَاطِلِ", t: "And do not consume one another's wealth unjustly", m: "Quran 2:188 — consuming wealth as metaphor" },
      { s: "يَأْكُلُ وَجْبَتَيْنِ فِي اليَوْم", t: "He eats two meals a day", m: "everyday — eating habits" },
    ],
    masdar: "أَكْل",
    fail: "آكِل",
    mafool: "مَأْكُول",
    conjugation: {
      past:    ["أَكَلَ","أَكَلَتْ","أَكَلَا","أَكَلَتَا","أَكَلُوا","أَكَلْنَ","أَكَلْتَ","أَكَلْتِ","أَكَلْتُمَا","أَكَلْتُمْ","أَكَلْتُنَّ","أَكَلْتُ","أَكَلْنَا"],
      present: ["يَأْكُلُ","تَأْكُلُ","يَأْكُلَانِ","تَأْكُلَانِ","يَأْكُلُونَ","يَأْكُلْنَ","تَأْكُلُ","تَأْكُلِينَ","تَأْكُلَانِ","تَأْكُلُونَ","تَأْكُلْنَ","آكُلُ","نَأْكُلُ"],
    },
  },
  {
    id: "shariba",
    ar: "شَرِبَ",
    root: "ش-ر-ب",
    form: "Form I",
    meaning: "to drink",
    meanings: ["to drink", "to absorb / imbibe"],
    sentence: "كُلُوا وَاشْرَبُوا هَنِيئًا بِمَا أَسْلَفْتُمْ",
    sentenceTr: "Eat and drink in enjoyment for what you put forth (Quran 69:24)",
    contexts: [
      { s: "وَأُشْرِبُوا فِي قُلُوبِهِمُ الْعِجْلَ بِكُفْرِهِمْ", t: "They were made to drink the love of the calf into their hearts through their disbelief", m: "Quran 2:93 — metaphorical absorption" },
      { s: "وَسَقَاهُمْ رَبُّهُمْ شَرَابًا طَهُورًا", t: "Their Lord will give them a pure drink", m: "Quran 76:21 — the drink of paradise" },
      { s: "يَشْرَبُ قَهْوَةً كُلَّ صَبَاح", t: "He drinks coffee every morning", m: "everyday — daily drinking habit" },
    ],
    masdar: "شُرْب",
    fail: "شَارِب",
    mafool: "مَشْرُوب",
    conjugation: {
      past:    ["شَرِبَ","شَرِبَتْ","شَرِبَا","شَرِبَتَا","شَرِبُوا","شَرِبْنَ","شَرِبْتَ","شَرِبْتِ","شَرِبْتُمَا","شَرِبْتُمْ","شَرِبْتُنَّ","شَرِبْتُ","شَرِبْنَا"],
      present: ["يَشْرَبُ","تَشْرَبُ","يَشْرَبَانِ","تَشْرَبَانِ","يَشْرَبُونَ","يَشْرَبْنَ","تَشْرَبُ","تَشْرَبِينَ","تَشْرَبَانِ","تَشْرَبُونَ","تَشْرَبْنَ","أَشْرَبُ","نَشْرَبُ"],
    },
  },
  {
    id: "dhahaba",
    ar: "ذَهَبَ",
    root: "ذ-ه-ب",
    form: "Form I",
    meaning: "to go",
    meanings: ["to go / leave", "to depart", "to pass away / vanish"],
    sentence: "اذْهَبْ أَنْتَ وَأَخُوكَ بِآيَاتِي",
    sentenceTr: "Go, you and your brother, with My signs (Quran 20:42)",
    contexts: [
      { s: "اذْهَبْ إِلَىٰ فِرْعَوْنَ إِنَّهُ طَغَىٰ", t: "Go to Pharaoh — indeed he has transgressed", m: "Quran 20:24 — Musa sent to Pharaoh" },
      { s: "وَلَا تَذْهَبْ نَفْسُكَ عَلَيْهِمْ حَسَرَاتٍ", t: "And do not let your soul perish over them in regret", m: "Quran 35:8 — the Prophet's grief" },
      { s: "يَذْهَبُ إِلَى العَمَلِ كُلَّ يَوْم", t: "He goes to work every day", m: "everyday — commuting" },
    ],
    masdar: "ذَهَاب",
    fail: "ذَاهِب",
    mafool: "مَذْهُوب إِلَيْهِ",
    conjugation: {
      past:    ["ذَهَبَ","ذَهَبَتْ","ذَهَبَا","ذَهَبَتَا","ذَهَبُوا","ذَهَبْنَ","ذَهَبْتَ","ذَهَبْتِ","ذَهَبْتُمَا","ذَهَبْتُمْ","ذَهَبْتُنَّ","ذَهَبْتُ","ذَهَبْنَا"],
      present: ["يَذْهَبُ","تَذْهَبُ","يَذْهَبَانِ","تَذْهَبَانِ","يَذْهَبُونَ","يَذْهَبْنَ","تَذْهَبُ","تَذْهَبِينَ","تَذْهَبَانِ","تَذْهَبُونَ","تَذْهَبْنَ","أَذْهَبُ","نَذْهَبُ"],
    },
  },
  {
    id: "jaa",
    ar: "جَاءَ",
    root: "ج-ي-أ",
    form: "Form I",
    meaning: "to come",
    meanings: ["to come", "to arrive", "to bring / produce"],
    sentence: "جَاءَ الحَقُّ وَزَهَقَ الْبَاطِلُ",
    sentenceTr: "Truth has come and falsehood has perished (Quran 17:81)",
    contexts: [
      { s: "وَجَاءَ رَبُّكَ وَالْمَلَكُ صَفًّا صَفًّا", t: "And your Lord comes and the angels in rows upon rows", m: "Quran 89:22 — Day of Judgment" },
      { s: "قَدْ جَاءَكُمُ الرَّسُولُ بِالْحَقِّ", t: "The Messenger has come to you with the truth", m: "Quran 4:170" },
      { s: "جَاءَ صَدِيقِي مِنْ بَعِيد", t: "My friend came from far away", m: "everyday — someone visiting" },
    ],
    masdar: "مَجِيء",
    fail: "جَائِي / قَادِم",
    mafool: "مَجِيء بِهِ",
    conjugation: {
      past:    ["جَاءَ","جَاءَتْ","جَاءَا","جَاءَتَا","جَاءُوا","جِئْنَ","جِئْتَ","جِئْتِ","جِئْتُمَا","جِئْتُمْ","جِئْتُنَّ","جِئْتُ","جِئْنَا"],
      present: ["يَجِيءُ","تَجِيءُ","يَجِيآنِ","تَجِيآنِ","يَجِيئُونَ","يَجِئْنَ","تَجِيءُ","تَجِيئِينَ","تَجِيآنِ","تَجِيئُونَ","تَجِئْنَ","أَجِيءُ","نَجِيءُ"],
    },
  },
  {
    id: "khallaqa",
    ar: "خَلَقَ",
    root: "خ-ل-ق",
    form: "Form I",
    meaning: "to create",
    meanings: ["to create", "to bring into existence", "to fashion / form"],
    sentence: "خَلَقَ الْإِنسَانَ مِنْ عَلَقٍ",
    sentenceTr: "He created man from a clinging clot (Quran 96:2)",
    contexts: [
      { s: "خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ فِي سِتَّةِ أَيَّامٍ", t: "He created the heavens and earth in six days", m: "Quran 7:54 — divine creation" },
      { s: "وَخَلَقْنَاكُمْ أَزْوَاجًا", t: "And We created you in pairs", m: "Quran 78:8 — human creation" },
      { s: "اللهُ خَالِقُ كُلِّ شَيْء", t: "Allah is the Creator of all things", m: "Quran 39:62 — comprehensive creation" },
    ],
    masdar: "خَلْق",
    fail: "خَالِق",
    mafool: "مَخْلُوق",
    conjugation: {
      past:    ["خَلَقَ","خَلَقَتْ","خَلَقَا","خَلَقَتَا","خَلَقُوا","خَلَقْنَ","خَلَقْتَ","خَلَقْتِ","خَلَقْتُمَا","خَلَقْتُمْ","خَلَقْتُنَّ","خَلَقْتُ","خَلَقْنَا"],
      present: ["يَخْلُقُ","تَخْلُقُ","يَخْلُقَانِ","تَخْلُقَانِ","يَخْلُقُونَ","يَخْلُقْنَ","تَخْلُقُ","تَخْلُقِينَ","تَخْلُقَانِ","تَخْلُقُونَ","تَخْلُقْنَ","أَخْلُقُ","نَخْلُقُ"],
    },
  },
  {
    id: "hadaa",
    ar: "هَدَى",
    root: "ه-د-ي",
    form: "Form I",
    meaning: "to guide",
    meanings: ["to guide", "to lead to the right path", "to show the way"],
    sentence: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
    sentenceTr: "Guide us to the straight path (Quran 1:6)",
    contexts: [
      { s: "إِنَّكَ لَا تَهْدِي مَنْ أَحْبَبْتَ وَلَٰكِنَّ اللهَ يَهْدِي مَنْ يَشَاءُ", t: "You do not guide whom you love but Allah guides whom He wills", m: "Quran 28:56 — guidance is from Allah" },
      { s: "وَاللهُ يَهْدِي مَنْ يَشَاءُ إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ", t: "And Allah guides whom He wills to a straight path", m: "Quran 2:213 — Allah's guidance" },
      { s: "هَدَاهُ صَدِيقُهُ إِلَى المَسْجِد", t: "His friend guided him to the mosque", m: "everyday — showing the way" },
    ],
    masdar: "هِدَايَة / هُدًى",
    fail: "هَادٍ",
    mafool: "مَهْدِيّ",
    conjugation: {
      past:    ["هَدَى","هَدَتْ","هَدَيَا","هَدَتَا","هَدَوْا","هَدَيْنَ","هَدَيْتَ","هَدَيْتِ","هَدَيْتُمَا","هَدَيْتُمْ","هَدَيْتُنَّ","هَدَيْتُ","هَدَيْنَا"],
      present: ["يَهْدِي","تَهْدِي","يَهْدِيَانِ","تَهْدِيَانِ","يَهْدُونَ","يَهْدِينَ","تَهْدِي","تَهْدِينَ","تَهْدِيَانِ","تَهْدُونَ","تَهْدِينَ","أَهْدِي","نَهْدِي"],
    },
  },
  {
    id: "taba",
    ar: "تَابَ",
    root: "ت-و-ب",
    form: "Form I",
    meaning: "to repent / turn back",
    meanings: ["to repent", "to turn back to Allah", "to return / relent"],
    sentence: "تُوبُوا إِلَى اللهِ تَوْبَةً نَصُوحًا",
    sentenceTr: "Repent to Allah with sincere repentance (Quran 66:8)",
    contexts: [
      { s: "إِنَّ اللهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ", t: "Indeed Allah loves those who constantly repent and loves those who purify themselves", m: "Quran 2:222" },
      { s: "مَنْ تَابَ مِنْ بَعْدِ ظُلْمِهِ وَأَصْلَحَ فَإِنَّ اللهَ يَتُوبُ عَلَيْهِ", t: "Whoever repents after wrongdoing and reforms — Allah will accept his repentance", m: "Quran 5:39" },
      { s: "تَابَ إِلَى اللهِ بَعْدَ سَنَوَاتٍ مِنَ الغَفْلَة", t: "He repented to Allah after years of heedlessness", m: "everyday spiritual return" },
    ],
    masdar: "تَوْبَة",
    fail: "تَائِب",
    mafool: "مَتُوب عَلَيْهِ",
    conjugation: {
      past:    ["تَابَ","تَابَتْ","تَابَا","تَابَتَا","تَابُوا","تُبْنَ","تُبْتَ","تُبْتِ","تُبْتُمَا","تُبْتُمْ","تُبْتُنَّ","تُبْتُ","تُبْنَا"],
      present: ["يَتُوبُ","تَتُوبُ","يَتُوبَانِ","تَتُوبَانِ","يَتُوبُونَ","يَتُبْنَ","تَتُوبُ","تَتُوبِينَ","تَتُوبَانِ","تَتُوبُونَ","يَتُبْنَ","أَتُوبُ","نَتُوبُ"],
    },
  },
  {
    id: "shakara",
    ar: "شَكَرَ",
    root: "ش-ك-ر",
    form: "Form I",
    meaning: "to be grateful / thank",
    meanings: ["to be grateful", "to thank", "to show gratitude"],
    sentence: "لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُمْ",
    sentenceTr: "If you are grateful I will surely increase you (Quran 14:7)",
    contexts: [
      { s: "وَاشْكُرُوا لِلهِ إِنْ كُنْتُمْ إِيَّاهُ تَعْبُدُونَ", t: "And be grateful to Allah if it is Him you worship", m: "Quran 2:172 — gratitude as worship" },
      { s: "وَقَلِيلٌ مِنْ عِبَادِيَ الشَّكُورُ", t: "And few of My servants are grateful", m: "Quran 34:13 — rarity of true gratitude" },
      { s: "شَكَرَ جَارَهُ عَلَى مُسَاعَدَتِه", t: "He thanked his neighbor for his help", m: "everyday — expressing thanks" },
    ],
    masdar: "شُكْر",
    fail: "شَاكِر",
    mafool: "مَشْكُور",
    conjugation: {
      past:    ["شَكَرَ","شَكَرَتْ","شَكَرَا","شَكَرَتَا","شَكَرُوا","شَكَرْنَ","شَكَرْتَ","شَكَرْتِ","شَكَرْتُمَا","شَكَرْتُمْ","شَكَرْتُنَّ","شَكَرْتُ","شَكَرْنَا"],
      present: ["يَشْكُرُ","تَشْكُرُ","يَشْكُرَانِ","تَشْكُرَانِ","يَشْكُرُونَ","يَشْكُرْنَ","تَشْكُرُ","تَشْكُرِينَ","تَشْكُرَانِ","تَشْكُرُونَ","تَشْكُرْنَ","أَشْكُرُ","نَشْكُرُ"],
    },
  },
  {
    id: "nasara",
    ar: "نَصَرَ",
    root: "ن-ص-ر",
    form: "Form I",
    meaning: "to help / give victory",
    meanings: ["to help / support", "to give victory to", "to defend"],
    sentence: "إِنْ تَنْصُرُوا اللهَ يَنْصُرْكُمْ",
    sentenceTr: "If you support Allah He will support you (Quran 47:7)",
    contexts: [
      { s: "وَنَصَرْنَاهُ مِنَ الْقَوْمِ الَّذِينَ كَذَّبُوا بِآيَاتِنَا", t: "And We supported him against the people who denied Our signs", m: "Quran 21:77 — Allah's support for prophets" },
      { s: "إِنَّ اللهَ يَنْصُرُ مَنْ يَنْصُرُهُ", t: "Indeed Allah will support whoever supports Him", m: "Quran 22:40" },
      { s: "نَصَرَ صَدِيقَهُ فِي وَقْتِ الحَاجَة", t: "He helped his friend in a time of need", m: "everyday — helping someone" },
    ],
    masdar: "نَصْر",
    fail: "نَاصِر",
    mafool: "مَنْصُور",
    conjugation: {
      past:    ["نَصَرَ","نَصَرَتْ","نَصَرَا","نَصَرَتَا","نَصَرُوا","نَصَرْنَ","نَصَرْتَ","نَصَرْتِ","نَصَرْتُمَا","نَصَرْتُمْ","نَصَرْتُنَّ","نَصَرْتُ","نَصَرْنَا"],
      present: ["يَنْصُرُ","تَنْصُرُ","يَنْصُرَانِ","تَنْصُرَانِ","يَنْصُرُونَ","يَنْصُرْنَ","تَنْصُرُ","تَنْصُرِينَ","تَنْصُرَانِ","تَنْصُرُونَ","تَنْصُرْنَ","أَنْصُرُ","نَنْصُرُ"],
    },
  },
  {
    id: "ghafara",
    ar: "غَفَرَ",
    root: "غ-ف-ر",
    form: "Form I",
    meaning: "to forgive",
    meanings: ["to forgive", "to pardon", "to cover / conceal (sins)"],
    sentence: "رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا",
    sentenceTr: "Our Lord forgive us our sins (Quran 3:193)",
    contexts: [
      { s: "إِنَّ اللهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ", t: "Indeed Allah forgives all sins — He is the Forgiving the Merciful", m: "Quran 39:53 — hope in Allah's forgiveness" },
      { s: "قُلْ رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ", t: "Say: My Lord forgive and have mercy — You are the best of the merciful", m: "Quran 23:118 — prophetic dua" },
      { s: "غَفَرَ لِأَخِيهِ مَا بَدَرَ مِنْهُ", t: "He forgave his brother for what had come from him", m: "everyday — human forgiveness" },
    ],
    masdar: "مَغْفِرَة / غُفْرَان",
    fail: "غَافِر",
    mafool: "مَغْفُور",
    conjugation: {
      past:    ["غَفَرَ","غَفَرَتْ","غَفَرَا","غَفَرَتَا","غَفَرُوا","غَفَرْنَ","غَفَرْتَ","غَفَرْتِ","غَفَرْتُمَا","غَفَرْتُمْ","غَفَرْتُنَّ","غَفَرْتُ","غَفَرْنَا"],
      present: ["يَغْفِرُ","تَغْفِرُ","يَغْفِرَانِ","تَغْفِرَانِ","يَغْفِرُونَ","يَغْفِرْنَ","تَغْفِرُ","تَغْفِرِينَ","تَغْفِرَانِ","تَغْفِرُونَ","تَغْفِرْنَ","أَغْفِرُ","نَغْفِرُ"],
    },
  },
  {
    id: "rajaa",
    ar: "رَجَعَ",
    root: "ر-ج-ع",
    form: "Form I",
    meaning: "to return",
    meanings: ["to return / go back", "to revert", "to refer back"],
    sentence: "إِنَّا لِلهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ",
    sentenceTr: "Indeed we belong to Allah and indeed to Him we will return (Quran 2:156)",
    contexts: [
      { s: "إِنَّا لِلهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ", t: "Indeed we belong to Allah and indeed to Him we will return", m: "Quran 2:156 — said at times of loss" },
      { s: "وَإِلَيْهِ تُرْجَعُونَ", t: "And to Him you will be returned", m: "Quran 2:245 — returning to Allah" },
      { s: "رَجَعَ إِلَى البَيْتِ بَعْدَ سَفَرٍ طَوِيل", t: "He returned home after a long trip", m: "everyday — coming back" },
    ],
    masdar: "رُجُوع",
    fail: "رَاجِع",
    mafool: "مَرْجُوع إِلَيْهِ",
    conjugation: {
      past:    ["رَجَعَ","رَجَعَتْ","رَجَعَا","رَجَعَتَا","رَجَعُوا","رَجَعْنَ","رَجَعْتَ","رَجَعْتِ","رَجَعْتُمَا","رَجَعْتُمْ","رَجَعْتُنَّ","رَجَعْتُ","رَجَعْنَا"],
      present: ["يَرْجِعُ","تَرْجِعُ","يَرْجِعَانِ","تَرْجِعَانِ","يَرْجِعُونَ","يَرْجِعْنَ","تَرْجِعُ","تَرْجِعِينَ","تَرْجِعَانِ","تَرْجِعُونَ","تَرْجِعْنَ","أَرْجِعُ","نَرْجِعُ"],
    },
  },
  {
    id: "fataha",
    ar: "فَتَحَ",
    root: "ف-ت-ح",
    form: "Form I",
    meaning: "to open / grant victory",
    meanings: ["to open", "to grant victory / conquest", "to begin / start"],
    sentence: "إِنَّا فَتَحْنَا لَكَ فَتْحًا مُبِينًا",
    sentenceTr: "Indeed We have granted you a clear victory (Quran 48:1)",
    contexts: [
      { s: "إِنَّا فَتَحْنَا لَكَ فَتْحًا مُبِينًا", t: "Indeed We have granted you a clear victory", m: "Quran 48:1 — Treaty of Hudaybiyyah" },
      { s: "وَلَوْ أَنَّ أَهْلَ الْقُرَىٰ آمَنُوا وَاتَّقَوْا لَفَتَحْنَا عَلَيْهِمْ بَرَكَاتٍ", t: "If the people of the towns had believed and had taqwa We would have opened upon them blessings", m: "Quran 7:96 — blessings as an opening" },
      { s: "فَتَحَ البَابَ وَدَخَلَ", t: "He opened the door and entered", m: "everyday — opening a door" },
    ],
    masdar: "فَتْح",
    fail: "فَاتِح",
    mafool: "مَفْتُوح",
    conjugation: {
      past:    ["فَتَحَ","فَتَحَتْ","فَتَحَا","فَتَحَتَا","فَتَحُوا","فَتَحْنَ","فَتَحْتَ","فَتَحْتِ","فَتَحْتُمَا","فَتَحْتُمْ","فَتَحْتُنَّ","فَتَحْتُ","فَتَحْنَا"],
      present: ["يَفْتَحُ","تَفْتَحُ","يَفْتَحَانِ","تَفْتَحَانِ","يَفْتَحُونَ","يَفْتَحْنَ","تَفْتَحُ","تَفْتَحِينَ","تَفْتَحَانِ","تَفْتَحُونَ","يَفْتَحْنَ","أَفْتَحُ","نَفْتَحُ"],
    },
  },
  {
    id: "qaraa",
    ar: "قَرَأَ",
    root: "ق-ر-أ",
    form: "Form I",
    meaning: "to read / recite",
    meanings: ["to read", "to recite", "to study"],
    sentence: "اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ",
    sentenceTr: "Read in the name of your Lord who created (Quran 96:1)",
    contexts: [
      { s: "اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ", t: "Read in the name of your Lord who created", m: "Quran 96:1 — the first revelation" },
      { s: "وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا", t: "And recite the Quran with measured recitation", m: "Quran 73:4 — command to recite properly" },
      { s: "يَقْرَأُ كِتَابًا كُلَّ أُسْبُوع", t: "He reads a book every week", m: "everyday — reading habit" },
    ],
    masdar: "قِرَاءَة",
    fail: "قَارِئ",
    mafool: "مَقْرُوء",
    conjugation: {
      past:    ["قَرَأَ","قَرَأَتْ","قَرَآ","قَرَأَتَا","قَرَءُوا","قَرَأْنَ","قَرَأْتَ","قَرَأْتِ","قَرَأْتُمَا","قَرَأْتُمْ","قَرَأْتُنَّ","قَرَأْتُ","قَرَأْنَا"],
      present: ["يَقْرَأُ","تَقْرَأُ","يَقْرَآنِ","تَقْرَآنِ","يَقْرَءُونَ","يَقْرَأْنَ","تَقْرَأُ","تَقْرَئِينَ","تَقْرَآنِ","تَقْرَءُونَ","يَقْرَأْنَ","أَقْرَأُ","نَقْرَأُ"],
    },
  },
  {
    id: "fahima",
    ar: "فَهِمَ",
    root: "ف-ه-م",
    form: "Form I",
    meaning: "to understand",
    meanings: ["to understand", "to comprehend", "to grasp the meaning of"],
    sentence: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
    sentenceTr: "My Lord expand my breast and ease my task (Quran 20:25-26)",
    contexts: [
      { s: "فَفَهَّمْنَاهَا سُلَيْمَانَ", t: "So We gave understanding of it to Sulayman", m: "Quran 21:79 — Allah giving understanding" },
      { s: "يَفْهَمُ القُرْآنَ بِسُرْعَة لِأَنَّهُ تَعَلَّمَ العَرَبِيَّة", t: "He understands the Quran quickly because he learned Arabic", m: "learning context" },
      { s: "فَهِمَ السُّؤَالَ وَأَجَابَ بِدِقَّة", t: "He understood the question and answered precisely", m: "everyday — comprehension" },
    ],
    masdar: "فَهْم",
    fail: "فَاهِم",
    mafool: "مَفْهُوم",
    conjugation: {
      past:    ["فَهِمَ","فَهِمَتْ","فَهِمَا","فَهِمَتَا","فَهِمُوا","فَهِمْنَ","فَهِمْتَ","فَهِمْتِ","فَهِمْتُمَا","فَهِمْتُمْ","فَهِمْتُنَّ","فَهِمْتُ","فَهِمْنَا"],
      present: ["يَفْهَمُ","تَفْهَمُ","يَفْهَمَانِ","تَفْهَمَانِ","يَفْهَمُونَ","يَفْهَمْنَ","تَفْهَمُ","تَفْهَمِينَ","تَفْهَمَانِ","تَفْهَمُونَ","يَفْهَمْنَ","أَفْهَمُ","نَفْهَمُ"],
    },
  },
  {
    id: "hajara",
    ar: "هَاجَرَ",
    root: "ه-ج-ر",
    form: "Form III",
    meaning: "to emigrate / migrate",
    meanings: ["to emigrate / migrate", "to leave for Allah's sake", "to abandon / forsake"],
    sentence: "وَمَنْ يُهَاجِرْ فِي سَبِيلِ اللهِ يَجِدْ فِي الْأَرْضِ مُرَاغَمًا كَثِيرًا",
    sentenceTr: "And whoever emigrates for the cause of Allah will find many places of refuge (Quran 4:100)",
    contexts: [
      { s: "إِنَّ الَّذِينَ آمَنُوا وَهَاجَرُوا وَجَاهَدُوا فِي سَبِيلِ اللهِ", t: "Indeed those who believed and emigrated and strove in the cause of Allah", m: "Quran 2:218 — the companions" },
      { s: "وَالَّذِينَ هَاجَرُوا فِي اللهِ مِنْ بَعْدِ مَا ظُلِمُوا", t: "Those who emigrated for Allah after they were wronged", m: "Quran 16:41 — reward for hijra" },
      { s: "هَاجَرَ إِلَى بَلَدٍ جَدِيدٍ لِطَلَبِ العِلْم", t: "He emigrated to a new country in search of knowledge", m: "everyday — moving for a purpose" },
    ],
    masdar: "هِجْرَة",
    fail: "مُهَاجِر",
    mafool: "مُهَاجَر إِلَيْهِ",
    conjugation: {
      past:    ["هَاجَرَ","هَاجَرَتْ","هَاجَرَا","هَاجَرَتَا","هَاجَرُوا","هَاجَرْنَ","هَاجَرْتَ","هَاجَرْتِ","هَاجَرْتُمَا","هَاجَرْتُمْ","هَاجَرْتُنَّ","هَاجَرْتُ","هَاجَرْنَا"],
      present: ["يُهَاجِرُ","تُهَاجِرُ","يُهَاجِرَانِ","تُهَاجِرَانِ","يُهَاجِرُونَ","يُهَاجِرْنَ","تُهَاجِرُ","تُهَاجِرِينَ","تُهَاجِرَانِ","تُهَاجِرُونَ","يُهَاجِرْنَ","أُهَاجِرُ","نُهَاجِرُ"],
    },
  },
  {
    id: "sadaqa",
    ar: "صَدَقَ",
    root: "ص-د-ق",
    form: "Form I",
    meaning: "to be truthful / tell the truth",
    meanings: ["to tell the truth / be truthful", "to verify / confirm", "to fulfill (a promise)"],
    sentence: "يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللهَ وَكُونُوا مَعَ الصَّادِقِينَ",
    sentenceTr: "O you who believe, fear Allah and be with the truthful (Quran 9:119)",
    contexts: [
      { s: "مِنَ الْمُؤْمِنِينَ رِجَالٌ صَدَقُوا مَا عَاهَدُوا اللهَ عَلَيْهِ", t: "Among the believers are men who have been true to their covenant with Allah", m: "Quran 33:23 — fulfilling promises" },
      { s: "إِنَّمَا يَخْشَى اللهَ مِنْ عِبَادِهِ الْعُلَمَاءُ", t: "Only those fear Allah among His servants who have knowledge", m: "Quran 35:28 — truthfulness leads to knowledge" },
      { s: "صَدَقَ فِي كَلَامِهِ وَلَمْ يَكْذِب", t: "He was truthful in his speech and did not lie", m: "everyday character description" },
    ],
    masdar: "صِدْق",
    fail: "صَادِق",
    mafool: "مُصَدَّق",
    conjugation: {
      past:    ["صَدَقَ","صَدَقَتْ","صَدَقَا","صَدَقَتَا","صَدَقُوا","صَدَقْنَ","صَدَقْتَ","صَدَقْتِ","صَدَقْتُمَا","صَدَقْتُمْ","صَدَقْتُنَّ","صَدَقْتُ","صَدَقْنَا"],
      present: ["يَصْدُقُ","تَصْدُقُ","يَصْدُقَانِ","تَصْدُقَانِ","يَصْدُقُونَ","يَصْدُقْنَ","تَصْدُقُ","تَصْدُقِينَ","تَصْدُقَانِ","تَصْدُقُونَ","يَصْدُقْنَ","أَصْدُقُ","نَصْدُقُ"],
    },
  },
  {
    id: "ajaba",
    ar: "أَجَابَ",
    root: "ج-و-ب",
    form: "Form IV",
    meaning: "to answer / respond",
    meanings: ["to answer / respond", "to grant / accept (dua)", "to reply"],
    sentence: "أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ",
    sentenceTr: "I answer the call of the caller when he calls upon Me (Quran 2:186)",
    contexts: [
      { s: "فَاسْتَجَابَ لَهُمْ رَبُّهُمْ أَنِّي لَا أُضِيعُ عَمَلَ عَامِلٍ مِنْكُمْ", t: "Their Lord responded to them: I will not allow the deeds of any worker among you to be lost", m: "Quran 3:195 — Allah answers the believers" },
      { s: "أَجَابَ الطَّالِبُ عَلَى جَمِيعِ الأَسْئِلَة", t: "The student answered all the questions", m: "everyday — answering questions" },
      { s: "أَجِبْ عَلَى رِسَالَتِي حِينَ تَسْتَطِيع", t: "Reply to my message when you can", m: "everyday — replying to messages" },
    ],
    masdar: "إِجَابَة",
    fail: "مُجِيب",
    mafool: "مُجَاب",
    conjugation: {
      past:    ["أَجَابَ","أَجَابَتْ","أَجَابَا","أَجَابَتَا","أَجَابُوا","أَجَبْنَ","أَجَبْتَ","أَجَبْتِ","أَجَبْتُمَا","أَجَبْتُمْ","أَجَبْتُنَّ","أَجَبْتُ","أَجَبْنَا"],
      present: ["يُجِيبُ","تُجِيبُ","يُجِيبَانِ","تُجِيبَانِ","يُجِيبُونَ","يُجِبْنَ","تُجِيبُ","تُجِيبِينَ","تُجِيبَانِ","تُجِيبُونَ","يُجِبْنَ","أُجِيبُ","نُجِيبُ"],
    },
  },
  {
    id: "arada",
    ar: "أَرَادَ",
    root: "ر-و-د",
    form: "Form IV",
    meaning: "to want / intend",
    meanings: ["to want / wish", "to intend / will", "to desire"],
    sentence: "وَاللهُ يُرِيدُ أَنْ يَتُوبَ عَلَيْكُمْ",
    sentenceTr: "And Allah wants to accept your repentance (Quran 4:27)",
    contexts: [
      { s: "يُرِيدُ اللهُ بِكُمُ الْيُسْرَ وَلَا يُرِيدُ بِكُمُ الْعُسْرَ", t: "Allah intends ease for you and does not intend hardship", m: "Quran 2:185 — Allah's will for ease" },
      { s: "مَا يُرِيدُ اللهُ لِيَجْعَلَ عَلَيْكُمْ مِنْ حَرَجٍ", t: "Allah does not intend to place any difficulty upon you", m: "Quran 5:6" },
      { s: "أُرِيدُ أَنْ أَتَعَلَّمَ العَرَبِيَّةَ بِطَلَاقَة", t: "I want to learn Arabic fluently", m: "everyday — expressing a goal" },
    ],
    masdar: "إِرَادَة",
    fail: "مُرِيد",
    mafool: "مُرَاد",
    conjugation: {
      past:    ["أَرَادَ","أَرَادَتْ","أَرَادَا","أَرَادَتَا","أَرَادُوا","أَرَدْنَ","أَرَدْتَ","أَرَدْتِ","أَرَدْتُمَا","أَرَدْتُمْ","أَرَدْتُنَّ","أَرَدْتُ","أَرَدْنَا"],
      present: ["يُرِيدُ","تُرِيدُ","يُرِيدَانِ","تُرِيدَانِ","يُرِيدُونَ","يُرِدْنَ","تُرِيدُ","تُرِيدِينَ","تُرِيدَانِ","تُرِيدُونَ","يُرِدْنَ","أُرِيدُ","نُرِيدُ"],
    },
  },
  {
    id: "taallama",
    ar: "تَعَلَّمَ",
    root: "ع-ل-م",
    form: "Form V",
    meaning: "to learn",
    meanings: ["to learn", "to study / acquire knowledge", "to find out"],
    sentence: "تَعَلَّمُوا الْعَرَبِيَّةَ فَإِنَّهَا مِنْ دِينِكُمْ",
    sentenceTr: "Learn Arabic for it is part of your religion (Umar ibn al-Khattab)",
    contexts: [
      { s: "وَعَلَّمَكَ مَا لَمْ تَكُنْ تَعْلَمُ", t: "And He taught you what you did not know", m: "Quran 4:113 — divine teaching" },
      { s: "تَعَلَّمُوا الْقُرْآنَ وَعَلِّمُوهُ النَّاسَ", t: "Learn the Quran and teach it to the people", m: "hadith — obligation to learn and teach" },
      { s: "يَتَعَلَّمُ لُغَةً جَدِيدَةً كُلَّ سَنَة", t: "He learns a new language every year", m: "everyday — continuous learning" },
    ],
    masdar: "تَعَلُّم",
    fail: "مُتَعَلِّم",
    mafool: "مُتَعَلَّم",
    conjugation: {
      past:    ["تَعَلَّمَ","تَعَلَّمَتْ","تَعَلَّمَا","تَعَلَّمَتَا","تَعَلَّمُوا","تَعَلَّمْنَ","تَعَلَّمْتَ","تَعَلَّمْتِ","تَعَلَّمْتُمَا","تَعَلَّمْتُمْ","تَعَلَّمْتُنَّ","تَعَلَّمْتُ","تَعَلَّمْنَا"],
      present: ["يَتَعَلَّمُ","تَتَعَلَّمُ","يَتَعَلَّمَانِ","تَتَعَلَّمَانِ","يَتَعَلَّمُونَ","يَتَعَلَّمْنَ","تَتَعَلَّمُ","تَتَعَلَّمِينَ","تَتَعَلَّمَانِ","تَتَعَلَّمُونَ","يَتَعَلَّمْنَ","أَتَعَلَّمُ","نَتَعَلَّمُ"],
    },
  },
  {
    id: "khalasa",
    ar: "خَلَصَ",
    root: "خ-ل-ص",
    form: "Form I",
    meaning: "to be saved / escape",
    meanings: ["to be saved / escape", "to be free of / rid of", "to be sincere / pure"],
    sentence: "فَلَمَّا اسْتَيْأَسُوا مِنْهُ خَلَصُوا نَجِيًّا",
    sentenceTr: "When they despaired of him they withdrew in private consultation (Quran 12:80)",
    contexts: [
      { s: "فَلَمَّا اسْتَيْأَسُوا مِنْهُ خَلَصُوا نَجِيًّا", t: "When they despaired they withdrew in private", m: "Quran 12:80 — brothers of Yusuf" },
      { s: "أَخْلَصَ عَمَلَهُ لِلهِ وَحْدَه", t: "He made his deeds purely for Allah alone", m: "Form IV — sincerity of worship" },
      { s: "خَلَصَ مِنَ الأَزْمَةِ بَعْدَ جُهْدٍ طَوِيل", t: "He escaped the crisis after a long struggle", m: "everyday — getting out of difficulty" },
    ],
    masdar: "خَلَاص",
    fail: "خَالِص",
    mafool: "مَخْلُوص مِنْهُ",
    conjugation: {
      past:    ["خَلَصَ","خَلَصَتْ","خَلَصَا","خَلَصَتَا","خَلَصُوا","خَلَصْنَ","خَلَصْتَ","خَلَصْتِ","خَلَصْتُمَا","خَلَصْتُمْ","خَلَصْتُنَّ","خَلَصْتُ","خَلَصْنَا"],
      present: ["يَخْلُصُ","تَخْلُصُ","يَخْلُصَانِ","تَخْلُصَانِ","يَخْلُصُونَ","يَخْلُصْنَ","تَخْلُصُ","تَخْلُصِينَ","تَخْلُصَانِ","تَخْلُصُونَ","يَخْلُصْنَ","أَخْلُصُ","نَخْلُصُ"],
    },
  },
  // ── TEMPLATE — copy this block and fill in for each new verb ──
  // {
  //   id: "kataba",                        // unique English key, no spaces
  //   ar: "كَتَبَ",                         // Arabic with full harakat
  //   root: "ك-ت-ب",                        // three root letters with dashes
  //   form: "Form I",                       // Form I … Form X
  //   meaning: "to write",                  // primary English meaning
  //   meanings: [                           // all meanings
  //     "to write",
  //     "to prescribe / ordain",
  //     "to record / register",
  //   ],
  //   sentence: "فَوَيْلٌ لِلَّذِينَ يَكْتُبُونَ الْكِتَابَ بِأَيْدِيهِمْ",   // example sentence (Arabic)
  //   sentenceTr: "Woe to those who write the scripture with their own hands (Quran 2:79)",
  //   contexts: [
  //     { s: "يَكْتُبُونَ الْكِتَابَ", t: "They write the scripture", m: "physical writing (Quran 2:79)" },
  //     { s: "كُتِبَ عَلَيْكُمُ الصِّيَامُ", t: "Fasting has been prescribed for you", m: "divine decree (Quran 2:183)" },
  //     { s: "كَتَبَ القَاضِي الحُكْمَ", t: "The judge wrote the verdict", m: "legal/administrative use" },
  //   ],
  //   masdar: "كِتَابَة / كَتْب",
  //   fail: "كَاتِب",
  //   mafool: "مَكْتُوب",
  //   conjugation: {
  //     // 13 pronouns: هو هي هما(م) هما(ف) هم هن أنت أنت أنتما أنتم أنتن أنا نحن
  //     past:    ["كَتَبَ","كَتَبَتْ","كَتَبَا","كَتَبَتَا","كَتَبُوا","كَتَبْنَ","كَتَبْتَ","كَتَبْتِ","كَتَبْتُمَا","كَتَبْتُمْ","كَتَبْتُنَّ","كَتَبْتُ","كَتَبْنَا"],
  //     present: ["يَكْتُبُ","تَكْتُبُ","يَكْتُبَانِ","تَكْتُبَانِ","يَكْتُبُونَ","يَكْتُبْنَ","تَكْتُبُ","تَكْتُبِينَ","تَكْتُبَانِ","تَكْتُبُونَ","تَكْتُبْنَ","أَكْتُبُ","نَكْتُبُ"],
  //   },
  // },
];